DROP TABLE NCL_HISTORICOEMAILANEXO;
DROP TABLE NCL_HISTORICOEMAIL;

CREATE TABLE NCL_HISTORICOEMAIL (
	ID					BIGINT			NOT NULL,
	DATA				VARCHAR(30)		NOT NULL,
	POSSUIANEXO			CHAR(1)			NOT NULL,
	ASSUNTO				VARCHAR(4000)		NULL,
	REMETENTE			VARCHAR(1000)	NOT NULL,
	MENSAGEM			VARCHAR(4000)		NULL,
	DESTINATARIOS		VARCHAR(4000)	NOT NULL,
	DESTINATARIOSCC		VARCHAR(4000)		NULL,
	DESTINATARIOSCCO	VARCHAR(4000)		NULL,
	CONTEXTO			VARCHAR(1000)		NULL
);


ALTER TABLE NCL_HISTORICOEMAIL
	ADD CONSTRAINT PK_NCL_HISTORICOEMAIL
	PRIMARY KEY(ID)
;

CREATE TABLE NCL_HISTORICOEMAILANEXO (
	IDHISTORICO			BIGINT			NOT NULL,
	NOMEANEXO			VARCHAR(1000)	NOT NULL,
	INDICE				INT				NOT NULL,
	BINARIOANEXO		IMAGE			NOT NULL
);	

ALTER TABLE NCL_HISTORICOEMAILANEXO
	ADD CONSTRAINT PK_NCL_HISTORICOEMAILANEXO
	PRIMARY KEY(IDHISTORICO, INDICE)
;

ALTER TABLE NCL_HISTORICOEMAILANEXO
	ADD CONSTRAINT FK_NCL_HISTORICOEMAILANEXO1
	FOREIGN KEY(IDHISTORICO)
	REFERENCES NCL_HISTORICOEMAIL(ID)
;

ALTER TABLE NCL_CNFGERAL ADD NOMEREMETENTE VARCHAR(255) NULL;

