INSERT INTO NCL_MODULO (IDMODULO, NOME) VALUES ('MOD.MP','Marcas e Patentes');
	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.MP','FUN.MP.001','Tipos de Patentes');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.001','OPE.MP.001.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.001','OPE.MP.001.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.001','OPE.MP.001.0003','Excluir');

	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.MP','FUN.MP.002','Cadastro de Inventor');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.002','OPE.MP.002.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.002','OPE.MP.002.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.002','OPE.MP.002.0003','Excluir');

	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.MP','FUN.MP.003','Procedimentos Internos');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.003','OPE.MP.003.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.003','OPE.MP.003.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.003','OPE.MP.003.0003','Excluir');


INSERT INTO NCL_MENUMODULO (IDMODULO, IMAGEM) VALUES ('MOD.MP','bogus');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.MP','FUN.MP.001','bogus','MP/cdTipoDePatente.aspx');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.MP','FUN.MP.002','bogus','MP/cdInventor.aspx');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.MP','FUN.MP.003','bogus','MP/cdProcedimentosInternos.aspx');