INSERT INTO NCL_MODULO (IDMODULO, NOME) VALUES ('MOD.CTP','Núcleo');
	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.CTP','FUN.CTP.001','Tipos de Patentes');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.CTP','FUN.CTP.001','OPE.CTP.001.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.CTP','FUN.CTP.001','OPE.CTP.001.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.CTP','FUN.CTP.001','OPE.CTP.001.0003','Excluir');

INSERT INTO NCL_MENUMODULO (IDMODULO, IMAGEM) VALUES ('MOD.CTP','bogus');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.CTP','FUN.CTP.001','bogus','Nucleo/TiposDePatenteCadastrado.aspx');