CREATE TABLE T13_SERVICOSPRESTADOS (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(80)		NOT NULL,
	VALOR				FLOAT				NULL,
	CARACTEDESCONTO		CHAR(1)				NULL
)
;

ALTER TABLE T13_SERVICOSPRESTADOS
	ADD CONSTRAINT PK_T13_SERVICOSPRESTADOS
	PRIMARY KEY (ID)
;
CREATE INDEX IDX_T13_SERVICOSPRESTADOS1
	ON T13_SERVICOSPRESTADOS(NOME)
;

CREATE TABLE T13_LANCAMENTODESERVICOS (
	ID					BIGINT			NOT NULL,
	NUMERO				INT				NOT NULL,
	IDCLIENTE			BIGINT			NOT NULL,
	DATA				INT				NOT NULL,
	ISSQN				VARCHAR(10)			NULL,
	ALIQUOTA			VARCHAR(10)			NULL,
	NATUREZADAOPERACAO	VARCHAR(15)			NULL,
	OBSERVACOES			VARCHAR(250)		NULL
)
;

ALTER TABLE T13_LANCAMENTODESERVICOS
	ADD CONSTRAINT PK_T13_LANCAMENTODESERVICOS
	PRIMARY KEY (ID)
;

ALTER TABLE T13_LANCAMENTODESERVICOS
	ADD CONSTRAINT FK_T13_LANCAMENTODESERVICOS
	FOREIGN KEY(IDCLIENTE)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_T13_LANCAMENTODESERVICOS1
	ON T13_LANCAMENTODESERVICOS(IDCLIENTE)
;

CREATE INDEX IDX_T13_LANCAMENTODESERVICOS2
	ON T13_LANCAMENTODESERVICOS(DATA)
;

CREATE TABLE T13_ITEMDELANCAMENTO (
	IDLANCAMENTO		BIGINT			NOT NULL,
	IDSERVICOPRESTADO	BIGINT			NOT NULL,
	VALOR				FLOAT			NOT NULL,
	UNIDADE				VARCHAR(3)			NULL,
	QUANTIDADE			SMALLINT			NULL,
	OBSERVACAO			VARCHAR(20)			NULL
);

ALTER TABLE T13_ITEMDELANCAMENTO
	ADD CONSTRAINT FK_T13_ITEMDELANCAMENTO1
	FOREIGN KEY(IDLANCAMENTO)
	REFERENCES T13_LANCAMENTODESERVICOS(ID)
;

ALTER TABLE T13_ITEMDELANCAMENTO
	ADD CONSTRAINT FK_T13_ITEMDELANCAMENTO2
	FOREIGN KEY(IDSERVICOPRESTADO)
	REFERENCES T13_SERVICOSPRESTADOS(ID)
;
