CREATE TABLE PET_VETERINARIO (
	IDPESSOA			BIGINT			NOT NULL,
	CRMV				VARCHAR(50)		NOT NULL,
	UF					SMALLINT		NOT NULL
)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT PK_PET_VETERINARIO
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT FK_PET_VETERINARIO
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE PET_ANIMAL (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DATADENASCIMENTO	INTEGER				NULL,
	SEXO				CHAR(1)			NOT NULL,
	RACA				VARCHAR(50)		NOT NULL,
	FOTO				VARCHAR(255)		NULL,
	IDPROPRIETARIO		BIGINT			NOT NULL,
	TIPOPESSOA			SMALLINT		NOT NULL,
	ESPECIE				CHAR(1)			NOT NULL
)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT PK_PET_ANIMAL
	PRIMARY KEY (ID)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT FK_PET_ANIMAL
	FOREIGN KEY(IDPROPRIETARIO)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_PET_ANIMAL
	ON PET_ANIMAL(NOME)
;

CREATE TABLE PET_ATENDANIMAL (
	ID					BIGINT			NOT NULL,
	IDANIMAL			BIGINT			NOT NULL,
	IDVETERINARIO		BIGINT			NOT NULL,
	DATAEHORA			VARCHAR(20)		NOT NULL
);

ALTER TABLE PET_ATENDANIMAL
	ADD CONSTRAINT PK_PET_ATENDANIMAL
	PRIMARY KEY (ID)
;

ALTER TABLE PET_ATENDANIMAL
	ADD CONSTRAINT FK_PET_ATENDANIMAL1
	FOREIGN KEY(IDANIMAL)
	REFERENCES PET_ANIMAL(ID)
;

ALTER TABLE PET_ATENDANIMAL
	ADD CONSTRAINT FK_PET_ATENDANIMAL2
	FOREIGN KEY(IDVETERINARIO)
	REFERENCES PET_VETERINARIO(IDPESSOA)
;

CREATE INDEX IDX_PET_ATENDANIMAL
	ON PET_ATENDANIMAL(DATAEHORA)
;


