DELETE FROM NCL_AGENCIABANCO;

ALTER TABLE NCL_AGENCIABANCO
 DROP CONSTRAINT "FK_NCL_AGENCIABANCO2";

ALTER TABLE NCL_BANCO
 DROP CONSTRAINT "FK_NCL_BANCO1";

DROP TABLE NCL_BANCO;
 
CREATE TABLE NCL_BANCO (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(255)	NOT NULL,
	NUMERO				SMALLINT		NOT NULL
)
;

ALTER TABLE NCL_BANCO
	ADD CONSTRAINT PK_NCL_BANCO
	PRIMARY KEY (ID)
;

CREATE INDEX IDX_NCL_BANCO
	ON NCL_BANCO(NUMERO)
;
 
ALTER TABLE NCL_AGENCIABANCO
	ADD CONSTRAINT FK_NCL_AGENCIABANCO2
	FOREIGN KEY(IDBANCO)
	REFERENCES NCL_BANCO(ID)
;

ALTER TABLE MP_REVISTA_PATENTE ADD NUMPROCESSOFORMATADO	VARCHAR(255) NULL;