INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.MP','FUN.MP.017','Gerar Boleto bancário');
INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.017','bogus','MP/frmBoletoBancarioCEF.aspx', NULL);

DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'OPE.MP.009.0004';
DELETE FROM NCL_OPERACAO WHERE IDOPERACAO = 'OPE.MP.009.0004';

DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'OPE.MP.009.0005';
DELETE FROM NCL_OPERACAO WHERE IDOPERACAO = 'OPE.MP.009.0005';

DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'OPE.MP.007.0004';
DELETE FROM NCL_OPERACAO WHERE IDOPERACAO = 'OPE.MP.007.0004';

DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'OPE.MP.007.0005';
DELETE FROM NCL_OPERACAO WHERE IDOPERACAO = 'OPE.MP.007.0005';

INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.007','OPE.MP.007.0004','Alterar data de despacho');	
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.MP','FUN.MP.009','OPE.MP.009.0004','Alterar data de despacho');

ALTER TABLE MP_MARCAS ADD MES VARCHAR(20) NULL;	

UPDATE MP_MARCAS SET IMAGEM_MARCA = '~/LOADS/IMAGENS/MARCAS/' + IMAGEM_MARCA WHERE IMAGEM_MARCA IS NOT NULL  AND IMAGEM_MARCA <> '' AND IMAGEM_MARCA NOT LIKE '%~/LOADS/IMAGENS/%';

UPDATE MP_MARCAS SET IMAGEM_MARCA = '~/LOADS/IMAGENS/MARCAS/sem_foto_g.gif' where IMAGEM_MARCA = '~/LOADS/IMAGENS/sem_foto_g.gif';

ALTER TABLE MP_PATENTE ADD MES VARCHAR(20) NULL;	