
CREATE TABLE NCL_HISTORICOEMAIL (
	ID					BIGINT			NOT NULL,
	DATA				VARCHAR(30)		NOT NULL,
	POSSUIANEXO			CHAR(1)			NOT NULL,
	ASSUNTO				VARCHAR(4000)		NULL,
	REMETENTE			VARCHAR(1000)	NOT NULL,
	MENSAGEM			VARCHAR(4000)		NULL,
	DESTINATARIOSCC		VARCHAR(4000)	NOT NULL,
	DESTINATARIOSCCO	VARCHAR(4000)		NULL,
	CONTEXTO			VARCHAR(1000)		NULL
);


ALTER TABLE NCL_HISTORICOEMAIL
	ADD CONSTRAINT PK_NCL_HISTORICOEMAIL
	PRIMARY KEY(ID)
;

CREATE TABLE NCL_HISTORICOEMAILANEXO (
	IDHISTORICO			BIGINT			NOT NULL,
	NOMEANEXO			VARCHAR(1000)	NOT NULL,
	INDICE				INT				NOT NULL,
	BINARIOANEXO		IMAGE			NOT NULL
);	

ALTER TABLE NCL_HISTORICOEMAILANEXO
	ADD CONSTRAINT PK_NCL_HISTORICOEMAILANEXO
	PRIMARY KEY(IDHISTORICO, INDICE)
;

ALTER TABLE NCL_HISTORICOEMAILANEXO
	ADD CONSTRAINT FK_NCL_HISTORICOEMAILANEXO1
	FOREIGN KEY(IDHISTORICO)
	REFERENCES NCL_HISTORICOEMAIL(ID)
;

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.NCL','FUN.NCL.020','Histórico de e-mails');
	INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.020','OPE.NCL.020.0001','Detalhar');
	INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.020','OPE.NCL.020.0002','Reenviar');
INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.NCL','FUN.NCL.020','bogus','Nucleo/frmHistoricoDeEmails.aspx', NULL);

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.MP','FUN.MP.018','Relatório de Manutenções');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.018','bogus','MP/frmRelatorioDeManutencoes.aspx', 'Relatórios');
	
INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.007','Gerenciamento de Itens Financeiros de Recebimento');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.007','OPE.FN.007.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.007','OPE.FN.007.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.007','OPE.FN.007.0003','Cancelar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.007','OPE.FN.007.0004','Efetivar cobrança');	
INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.FN','FUN.FN.007','bogus','FN/frmGerenciamentoDeItensFinanceiros.aspx', NULL);

DELETE FROM FN_ITEMFINANREC;

DELETE FROM MP_INTERFACEFN;

CREATE TABLE NCL_PESSOAEMAIL(
	IDPESSOA VARCHAR(255) NOT NULL,
	ENDEMAIL VARCHAR(255) NOT NULL);

ALTER TABLE NCL_PESSOAEMAIL
	ADD CONSTRAINT PK_NCL_PESSOAEMAIL
	PRIMARY KEY(IDPESSOA, ENDEMAIL);

ALTER TABLE NCL_PESSOAEMAIL
	ADD CONSTRAINT FK_NCL_PESSOAEMAIL1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID);

ALTER TABLE NCL_PESSOAEMAIL
	ADD CONSTRAINT UC_NCL_PESSOAEMAIL1 UNIQUE (IDPESSOA, ENDEMAIL); 

--Rodar o Migrador antes de excluir a coluna da tabela
ALTER TABLE NCL_PESSOA DROP COLUMN ENDEMAIL;

ALTER TABLE NCL_PESSOATELEFONE ADD CONTATO VARCHAR(255) NULL;