CREATE TABLE NCL_IDENTIFICADOR (
	NUMHIGH				NUMBER(11)		NOT NULL
)
;

CREATE TABLE NCL_MUNICIPIO (
	ID					NUMBER(11)		NOT NULL,
	NOME				VARCHAR2(30)	NOT NULL,
	UF					NUMBER(5)		NOT NULL,
	CEP					NUMBER(9)			NULL
)
;

ALTER TABLE NCL_MUNICIPIO
	ADD CONSTRAINT PK_NCL_MUNIC
	PRIMARY KEY(ID)
;

CREATE INDEX IDX_NCL_MUNICIPIO1
	ON NCL_MUNICIPIO(NOME)
;

CREATE TABLE NCL_GRUPO (
	ID					NUMBER(11)		NOT NULL,
	NOME				VARCHAR2(30)	NOT NULL,
	STATUS				CHAR(1)			NOT NULL
)
;

ALTER TABLE NCL_GRUPO
	ADD CONSTRAINT PK_NCL_GRUPO
	PRIMARY KEY(ID)
;

CREATE INDEX IDX_NCL_GRUPO1
	ON NCL_GRUPO(NOME)
;

CREATE TABLE NCL_MODULO (
	IDMODULO			VARCHAR2(7)		NOT NULL,
	NOME				VARCHAR2(30)	NOT NULL
)
;

ALTER TABLE NCL_MODULO
	ADD CONSTRAINT PK_NCL_MODULO
	PRIMARY KEY(IDMODULO)
;

CREATE TABLE NCL_FUNCAO (
	IDMODULO			VARCHAR2(7)		NOT NULL,
	IDFUNCAO			VARCHAR2(11)	NOT NULL,
	NOME				VARCHAR2(100)	NOT NULL
)
;

ALTER TABLE NCL_FUNCAO
	ADD CONSTRAINT PK_NCL_FUNCAO
	PRIMARY KEY(IDMODULO, IDFUNCAO)
;

ALTER TABLE NCL_FUNCAO
	ADD CONSTRAINT FK_NCL_FUNCAO
	FOREIGN KEY(IDMODULO)
	REFERENCES NCL_MODULO(IDMODULO)
;

CREATE TABLE NCL_OPERACAO (
	IDMODULO			VARCHAR2(7)		NOT NULL,
	IDFUNCAO			VARCHAR2(11)	NOT NULL,
	IDOPERACAO			VARCHAR2(16)	NOT NULL,
	NOME				VARCHAR2(30)	NOT NULL
)
;

ALTER TABLE NCL_OPERACAO
	ADD CONSTRAINT PK_NCL_OPERACAO
	PRIMARY KEY(IDMODULO, IDFUNCAO, IDOPERACAO)
;

ALTER TABLE NCL_OPERACAO
	ADD CONSTRAINT FK_NCL_OPERACAO
	FOREIGN KEY(IDMODULO, IDFUNCAO)
	REFERENCES NCL_FUNCAO(IDMODULO,IDFUNCAO)
;

CREATE TABLE NCL_MENUMODULO (
	IDMODULO			VARCHAR2(7)		NOT NULL,
	IMAGEM				VARCHAR2(255)	NOT NULL
)
;

ALTER TABLE NCL_MENUMODULO
	ADD CONSTRAINT PK_NCL_MENUMODULO
	PRIMARY KEY (IDMODULO)
;

ALTER TABLE NCL_MENUMODULO
	ADD CONSTRAINT FK_NCL_MENUMODULO
	FOREIGN KEY(IDMODULO)
	REFERENCES NCL_MODULO(IDMODULO)
;

CREATE TABLE NCL_MENUFUNCAO (
	IDMODULO			VARCHAR2(7)		NOT NULL,
	IDFUNCAO			VARCHAR2(11)	NOT NULL,
	IMAGEM				VARCHAR2(100)	NOT NULL,
	URL					VARCHAR2(100)	NOT NULL
)
;

ALTER TABLE NCL_MENUFUNCAO
	ADD CONSTRAINT PK_NCL_MENUFUNCAO
	PRIMARY KEY (IDMODULO,IDFUNCAO)
;

ALTER TABLE NCL_MENUFUNCAO
	ADD CONSTRAINT FK_NCL_MENUFUNCAO
	FOREIGN KEY(IDMODULO, IDFUNCAO)
	REFERENCES NCL_FUNCAO(IDMODULO, IDFUNCAO)
;

CREATE TABLE NCL_AUTORIZACAO (
	IDGRUPO				NUMBER(11)		NOT NULL,
	IDDIRETIVA			VARCHAR2(20)	NOT NULL
)
;

ALTER TABLE NCL_AUTORIZACAO
	ADD CONSTRAINT PK_NCL_AUTORIZACAO
	PRIMARY KEY (IDGRUPO, IDDIRETIVA)
;

ALTER TABLE NCL_AUTORIZACAO
	ADD CONSTRAINT FK_NCL_AUTORIZACAO
	FOREIGN KEY(IDGRUPO)
	REFERENCES NCL_GRUPO(ID)
;


CREATE TABLE NCL_PESSOA (
	ID					NUMBER(11)			NOT NULL,
	NOME				VARCHAR2(100)		NOT NULL,
	TIPO				NUMBER(5)			NOT NULL,
	ENDEMAIL			VARCHAR2(255)		NULL,
	SITE				VARCHAR2(255)		NULL,
	IDBANCO				NUMBER(11)			NULL,
	IDAGENCIA			NUMBER(11)			NULL,
	CNTACORRENTE		VARCHAR2(50)		NULL,
	TIPOCNTACORRENTE	NUMBER(5)			NULL
)
;

ALTER TABLE NCL_PESSOA
	ADD CONSTRAINT PK_NCL_PESSOA
	PRIMARY KEY (ID)
;

CREATE INDEX IDX_NCL_PESSOA1
	ON NCL_PESSOA(NOME)
;


CREATE TABLE NCL_PESSOAFISICA (
	IDPESSOA			NUMBER(11)			NOT NULL,
	DATANASCIMENTO		NUMBER(9)				NULL,
	ESTADOCIVIL			CHAR(1)					NULL,
	NACIONALIDADE		CHAR(1)					NULL,
	RACA				CHAR(1)					NULL,
	SEXO				CHAR(1)					NULL,
	NOMEMAE				VARCHAR2(100)			NULL,
	NOMEPAI				VARCHAR2(100)			NULL,
	NUMERORG			VARCHAR2(30)			NULL,
	ORGEXPEDITOR		VARCHAR2(20)			NULL,
	DATAEXP				NUMBER(9)				NULL,
	UFEXP				NUMBER(5)				NULL,
	CPF					CHAR(11)				NULL,
	NATURALIDADE		NUMBER(11)				NULL,
	FOTO				VARCHAR2(4000)			NULL
)
;

ALTER TABLE NCL_PESSOAFISICA
	ADD CONSTRAINT PK_NCL_PESSOAFISICA
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE NCL_PESSOAFISICA
	ADD CONSTRAINT FK_NCL_PESSOAFISICA1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE NCL_PESSOAJURIDICA (
	IDPESSOA			NUMBER(11)			NOT NULL,
	NOMEFANTASIA		VARCHAR2(100)			NULL,
	CNPJ				CHAR(14)				NULL,
	IE					VARCHAR2(14)			NULL,
	IM					VARCHAR2(20)			NULL,
	LOGOMARCA			VARCHAR2(4000)			NULL
)
;

ALTER TABLE NCL_PESSOAJURIDICA
	ADD CONSTRAINT PK_NCL_PESSOAJURIDICA
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE NCL_PESSOAJURIDICA
	ADD CONSTRAINT FK_NCL_PESSOAJURIDICA1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE NCL_EMPRESA (
	IDPESSOA			NUMBER(11)			NOT NULL,
	DTATIVACAO			NUMBER(9)			NOT NULL
)
;

ALTER TABLE NCL_EMPRESA
	ADD CONSTRAINT PK_NCL_EMPRESA
	PRIMARY KEY (IDPessoa)
;

ALTER TABLE NCL_EMPRESA
	ADD CONSTRAINT FK_NCL_EMPRESA1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE NCL_OPERADOR (
	IDPESSOA			NUMBER(11)			NOT NULL,
	TIPOPESSOA			NUMBER(5)			NOT NULL,
	LOGIN				VARCHAR2(255)		NOT NULL,
	STATUS				CHAR(1)				NOT NULL
)
;

ALTER TABLE NCL_OPERADOR
	ADD CONSTRAINT PK_NCL_OPERADOR
	PRIMARY KEY (IDPessoa)
;
CREATE INDEX IDX_NCL_OPERADOR1
	ON NCL_OPERADOR(LOGIN)
;

ALTER TABLE NCL_OPERADOR
	ADD CONSTRAINT FK_NCL_OPERADOR1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE NCL_PERFIL (
	IDUSUARIO			NUMBER(11)			NOT NULL,
	IMAGEMDESKTOP		VARCHAR2(100)		NOT NULL,
	TEMA				VARCHAR2(20)		NOT NULL
)
;

ALTER TABLE NCL_PERFIL
	ADD CONSTRAINT PK_NCL_PERFIL
	PRIMARY KEY (IDUSUARIO)
;

ALTER TABLE NCL_PERFIL
	ADD CONSTRAINT FK_NCL_PERFIL
	FOREIGN KEY(IDUSUARIO)
	REFERENCES NCL_OPERADOR(IDPESSOA)
;

CREATE TABLE NCL_GRPOPE (
	IDOPERADOR			NUMBER(11)			NOT NULL,
	IDGRUPO				NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_GRPOPE
	ADD CONSTRAINT PK_NCL_GRPOPE
	PRIMARY KEY (IDOPERADOR,IDGRUPO)
;

ALTER TABLE NCL_GRPOPE
	ADD CONSTRAINT FK_NCL_GRPOPE1
	FOREIGN KEY(IDOPERADOR)
	REFERENCES NCL_OPERADOR(IDPESSOA)
;

ALTER TABLE NCL_GRPOPE
	ADD CONSTRAINT FK_NCL_GRPOPE2
	FOREIGN KEY(IDGRUPO)
	REFERENCES NCL_GRUPO(ID)
;

CREATE TABLE NCL_SNHOP (
	IDOPERADOR			NUMBER(11)			NOT NULL,
	SENHA				VARCHAR2(4000)		NOT NULL,
	DATACADASTRO		VARCHAR2(20)		NOT NULL
)
;

ALTER TABLE NCL_SNHOP
	ADD CONSTRAINT PK_NCL_SNHOP
	PRIMARY KEY (IDOPERADOR)
;

ALTER TABLE NCL_SNHOP
	ADD CONSTRAINT FK_NCL_SNHOP
	FOREIGN KEY(IDOPERADOR)
	REFERENCES NCL_OPERADOR(IDPESSOA)
;

CREATE TABLE NCL_GRUPO_DE_ATIVIDADE (
	ID					NUMBER(11)			NOT NULL,
	NOME				VARCHAR2(30)		NOT NULL
)
;

ALTER TABLE NCL_GRUPO_DE_ATIVIDADE
	ADD CONSTRAINT PK_NCL_GRUPO_DE_ATIVIDADE
	PRIMARY KEY(ID)
;

CREATE INDEX IDX_NCL_GRUPO_DE_ATIVIDADE1
	ON NCL_GRUPO_DE_ATIVIDADE(NOME)
;

CREATE TABLE NCL_CLIENTE (
	IDPESSOA			NUMBER(11)			NOT NULL,
	TIPOPESSOA			NUMBER(5)			NOT NULL,
	DTCADASTRO			NUMBER(9)			NOT NULL,
	INFOADICIONAL		VARCHAR2(4000)			NULL,
	FAIXASALARIAL		FLOAT					NULL,
	DESCONTOAUTOMATICO	FLOAT					NULL,
	VLRMAXCOMPRAS		FLOAT					NULL,
	SALDOCOMPRAS		FLOAT					NULL,
	IDEMPRESA			NUMBER(11)			NOT NULL,
	NUMREGISTRO			VARCHAR2(255)			NULL,
	DTREGISTRO			NUMBER(9)				NULL,
	IDGRPATIVIDADE		NUMBER(11)				NULL
)
;

ALTER TABLE NCL_CLIENTE
	ADD CONSTRAINT PK_NCL_CLIENTE
	PRIMARY KEY (IDPessoa)
;

ALTER TABLE NCL_CLIENTE
	ADD CONSTRAINT FK_NCL_CLIENTE1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

ALTER TABLE NCL_CLIENTE
	ADD CONSTRAINT FK_NCL_CLIENTE2
	FOREIGN KEY(IDGRPATIVIDADE)
	REFERENCES NCL_GRUPO_DE_ATIVIDADE(ID)
;

ALTER TABLE NCL_CLIENTE
	ADD CONSTRAINT FK_NCL_CLIENTE3
	FOREIGN KEY(IDEMPRESA)
	REFERENCES NCL_EMPRESA(IDPESSOA)
;

CREATE TABLE NCL_ATALHO (
	ID					VARCHAR2(100)		NOT NULL,
	NOME				VARCHAR2(100)		NOT NULL,
	TIPO				CHAR(1)				NOT NULL,
	URL					VARCHAR2(4000)		NOT NULL,
	IMAGEM				VARCHAR2(4000)		NOT NULL,
	IDUSUARIO			NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_ATALHO
	ADD CONSTRAINT PK_NCL_ATALHO
	PRIMARY KEY (ID,IDUSUARIO)
;

CREATE INDEX IDX_NCL_ATALHO
	ON NCL_ATALHO(IDUSUARIO)
;

CREATE TABLE NCL_BANCO (
	IDPESSOA			NUMBER(11)			NOT NULL,
	NUMERO				NUMBER(5)			NOT NULL
)
;

ALTER TABLE NCL_BANCO
	ADD CONSTRAINT PK_NCL_BANCO
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE NCL_BANCO
	ADD CONSTRAINT FK_NCL_BANCO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_NCL_BANCO
	ON NCL_BANCO(NUMERO)
;

CREATE TABLE NCL_AGENCIABANCO (
	IDPESSOA			NUMBER(11)			NOT NULL,
	IDBANCO				NUMBER(11)			NOT NULL,
	NUMERO				VARCHAR2(50)		NOT NULL
)
;

ALTER TABLE NCL_AGENCIABANCO
	ADD CONSTRAINT PK_NCL_AGENCIABANCO
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE NCL_AGENCIABANCO
	ADD CONSTRAINT FK_NCL_AGENCIABANCO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

ALTER TABLE NCL_AGENCIABANCO
	ADD CONSTRAINT FK_NCL_AGENCIABANCO2
	FOREIGN KEY(IDBANCO)
	REFERENCES NCL_BANCO(IDPESSOA)
;

CREATE INDEX IDX_NCL_AGENCIABANCO
	ON NCL_AGENCIABANCO(NUMERO)
;

CREATE TABLE NCL_TIPO_ENDERECO (
	ID					NUMBER(11)			NOT NULL,
	NOME				VARCHAR2(255)		NOT NULL
)
;

ALTER TABLE NCL_TIPO_ENDERECO
	ADD CONSTRAINT PK_NCL_TIPO_ENDERECO
	PRIMARY KEY (ID)
;

CREATE INDEX IDX_NCL_TIPO_ENDERECO1
	ON NCL_TIPO_ENDERECO(NOME)
;

CREATE TABLE NCL_PESSOAENDERECO (
	IDPESSOA			NUMBER(11)			NOT NULL,
	TIPO				NUMBER(11)			NOT NULL,
	LOGRADOURO			VARCHAR2(255)			NULL,
	COMPLEMENTO			VARCHAR2(255)			NULL,
	IDMUNICIPIO			NUMBER(11)				NULL,
	CEP					NUMBER(11)				NULL,
	BAIRRO				VARCHAR2(100)			NULL
)
;

ALTER TABLE NCL_PESSOAENDERECO
	ADD CONSTRAINT PK_NCL_PESSOAENDERECO
	PRIMARY KEY (IDPESSOA, TIPO)
;

ALTER TABLE NCL_PESSOAENDERECO
	ADD CONSTRAINT FK_NCL_PESSOAENDERECO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

ALTER TABLE NCL_PESSOAENDERECO
	ADD CONSTRAINT FK_NCL_PESSOAENDERECO2
	FOREIGN KEY(TIPO)
	REFERENCES NCL_TIPO_ENDERECO(ID)
;

CREATE TABLE NCL_PESSOATELEFONE (
	IDPESSOA			NUMBER(11)			NOT NULL,
	DDD					NUMBER(5)			NOT NULL,
	NUMERO				NUMBER(11)			NOT NULL,
	TIPO				NUMBER(5)			NOT NULL,
	INDICE				NUMBER(5)			NOT NULL
)
;

ALTER TABLE NCL_PESSOATELEFONE
	ADD CONSTRAINT PK_NCL_PESSOATELEFONE
	PRIMARY KEY (IDPESSOA, DDD, NUMERO, TIPO)
;

ALTER TABLE NCL_PESSOATELEFONE
	ADD CONSTRAINT FK_NCL_PESSOATELEFONE1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

ALTER TABLE NCL_PESSOA
	ADD CONSTRAINT FK_NCL_PESSOA2
	FOREIGN KEY(IDAGENCIA)
	REFERENCES NCL_AGENCIABANCO(IDPESSOA)	
;

CREATE TABLE NCL_CNFAGENDAUSU (
	IDPESSOA			NUMBER(11)			NOT NULL,
	HORAINICO			NUMBER(5)			NOT NULL,
	HORAFIM				NUMBER(5)			NOT NULL,
	INTERVALO			NUMBER(5)			NOT NULL,
	IDPESSOAPADRAO		NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_CNFAGENDAUSU
	ADD CONSTRAINT PK_NCL_CNFAGENDAUSU
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE NCL_CNFAGENDAUSU
	ADD CONSTRAINT FK_NCL_CNFAGENDAUSU1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

ALTER TABLE NCL_CNFAGENDAUSU
	ADD CONSTRAINT FK_NCL_CNFAGENDAUSU2
	FOREIGN KEY(IDPESSOAPADRAO)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE NCL_COMPROMISSO (
	ID					NUMBER(11)			NOT NULL,
	IDPESSOA			NUMBER(11)			NOT NULL,
	INICIO				VARCHAR2(20)		NOT NULL,
	FIM					VARCHAR2(20)		NOT NULL,
	ASSUNTO				VARCHAR2(4000)		NOT NULL,
	LOCAL				VARCHAR2(4000)			NULL,
	DESCRICAO			VARCHAR2(4000)			NULL,
	STATUS				CHAR(1)				NOT NULL
)
;

ALTER TABLE NCL_COMPROMISSO
	ADD CONSTRAINT PK_NCL_COMPROMISSO
	PRIMARY KEY (ID)
;

ALTER TABLE NCL_COMPROMISSO
	ADD CONSTRAINT FK_NCL_COMPROMISSO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_NCL_COMPROMISSO1
	ON NCL_COMPROMISSO(INICIO)
;

CREATE INDEX IDX_NCL_COMPROMISSO2
	ON NCL_COMPROMISSO(FIM)
;

CREATE TABLE NCL_TAREFA (
	ID					NUMBER(11)			NOT NULL,
	IDPESSOA			NUMBER(11)			NOT NULL,
	INICIO				VARCHAR2(20)		NOT NULL,
	FIM					VARCHAR2(20)		NOT NULL,
	ASSUNTO				VARCHAR2(4000)		NOT NULL,
	DESCRICAO			VARCHAR2(4000)			NULL,
	PRIORIDADE			CHAR(1)				NOT NULL,
	STATUS				CHAR(1)				NOT NULL
)
;

ALTER TABLE NCL_TAREFA
	ADD CONSTRAINT PK_NCL_TAREFA
	PRIMARY KEY (ID)
;

ALTER TABLE NCL_TAREFA
	ADD CONSTRAINT FK_NCL_TAREFA1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_NCL_TAREFA1
	ON NCL_TAREFA(INICIO)
;

CREATE INDEX IDX_NCL_TAREFA2
	ON NCL_TAREFA(FIM)
;

CREATE TABLE NCL_LEMBRETE (
	ID					NUMBER(11)			NOT NULL,
	IDPESSOA			NUMBER(11)			NOT NULL,
	INICIO				VARCHAR2(20)		NOT NULL,
	FIM					VARCHAR2(20)		NOT NULL,
	ASSUNTO				VARCHAR2(4000)		NOT NULL,
	LOCAL				VARCHAR2(4000)			NULL,
	DESCRICAO			VARCHAR2(4000)			NULL,
	STATUS				CHAR(1)				NOT NULL
)
;

ALTER TABLE NCL_LEMBRETE
	ADD CONSTRAINT PK_NCL_LEMBRETE
	PRIMARY KEY (ID)
;

ALTER TABLE NCL_LEMBRETE
	ADD CONSTRAINT FK_NCL_LEMBRETE1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_NCL_LEMBRETE1
	ON NCL_LEMBRETE(INICIO)
;

CREATE INDEX IDX_NCL_LEMBRETE2
	ON NCL_LEMBRETE(FIM)
;

CREATE TABLE NCL_CNFGERAL (
	NOTIFERROSREMAIL		CHAR(1)			NOT NULL,
	EMAILREMETNOTIFERROS	VARCHAR2(255)		NULL,
	REMETENTEPADRAO			VARCHAR2(255)		NULL,
	HABILITARSSL			CHAR(1)				NULL,
	PORTA					NUMBER(5)			NULL,
	REQUERAUTENTICACAO		CHAR(1)				NULL,
	SHNUSUSERVSAIDA			VARCHAR2(255)		NULL,
	USUSERVSAIDA			VARCHAR2(255)		NULL,
	SERVSAIDA				VARCHAR2(255)		NULL,
	TIPOSERVSAIDA			CHAR(1)				NULL,
	TXTCOMPRO				VARCHAR2(50)		NULL,
	TXTCOMPROENTRELNH		CHAR(1)			NOT NULL,
	TXTLEMBRE				VARCHAR2(50)		NULL,
	TXTLEMBREENTRELNH		CHAR(1)			NOT NULL,
	TXTTARE					VARCHAR2(50)		NULL,
	TXTTAREENTRELNH			CHAR(1)			NOT NULL,
	TXTCABAGEN				VARCHAR2(50)	NOT NULL,
	APRELNHCABAGEN			CHAR(1)			NOT NULL,
	APRELNHRODAGEN			CHAR(1)			NOT NULL
)
;

INSERT INTO NCL_CNFGERAL (NOTIFERROSREMAIL, EMAILREMETNOTIFERROS, REMETENTEPADRAO, HABILITARSSL, PORTA, REQUERAUTENTICACAO, SHNUSUSERVSAIDA, USUSERVSAIDA, SERVSAIDA, TIPOSERVSAIDA, TXTCOMPRO, TXTCOMPROENTRELNH, TXTLEMBRE, TXTLEMBREENTRELNH, TXTTARE, TXTTAREENTRELNH, TXTCABAGEN, APRELNHCABAGEN, APRELNHRODAGEN) VALUES('S', 'HERMES@SIMPLETI.COM.BR', 'HERMES@SIMPLETI.COM.BR', 'N', 25, 'S', 'CJORP8Z5JEWM4ECX+ENUAG==', 'HERMES@SIMPLETI.COM.BR', 'MAIL.SIMPLETI.COM.BR', '0', 'Compromissos ', 'N', 'Lembretes ', 'N', 'Tarefas ', 'N', 'Agenda ', 'N', 'N');


CREATE TABLE NCL_FORNECEDOR (
	IDPESSOA			NUMBER(11)			NOT NULL,
	TIPOPESSOA			NUMBER(5)			NOT NULL,
	DTCADASTRO			NUMBER(9)			NOT NULL,
	INFOADICIONAL		VARCHAR2(4000)		NULL,
	IDEMPRESA			NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_FORNECEDOR
	ADD CONSTRAINT PK_NCL_FORNECEDOR
	PRIMARY KEY (IDPessoa)
;

ALTER TABLE NCL_FORNECEDOR
	ADD CONSTRAINT FK_NCL_FORNECEDOR1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE NCL_CONTATOFORNECEDOR (
	IDPFORNECEDOR		NUMBER(11)			NOT NULL,
	IDPESSOACONTATO		NUMBER(11)			NOT NULL,
	IDEMPRESA			NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_CONTATOFORNECEDOR
	ADD CONSTRAINT PK_NCL_CONTATOFORNECEDOR
	PRIMARY KEY (IDPFORNECEDOR,IDPESSOACONTATO)
;

ALTER TABLE NCL_CONTATOFORNECEDOR
	ADD CONSTRAINT FK_NCL_CONTATOFORNECEDOR1
	FOREIGN KEY(IDPFORNECEDOR)
	REFERENCES NCL_FORNECEDOR(IDPESSOA)
;

ALTER TABLE NCL_CONTATOFORNECEDOR
	ADD CONSTRAINT FK_NCL_CONTATOFORNECEDOR2
	FOREIGN KEY(IDPESSOACONTATO)
	REFERENCES NCL_PESSOA(ID)
;



CREATE TABLE NCL_VISOPEEMP (
	IDOPERADOR			NUMBER(11)			NOT NULL,
	IDEMPRESA			NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_VISOPEEMP
	ADD CONSTRAINT PK_NCL_VISOPEEMP
	PRIMARY KEY (IDOPERADOR,IDEMPRESA)
;

ALTER TABLE NCL_VISOPEEMP
	ADD CONSTRAINT FK_NCL_VISOPEEMP1
	FOREIGN KEY(IDOPERADOR)
	REFERENCES NCL_OPERADOR(IDPESSOA)
;

ALTER TABLE NCL_VISOPEEMP
	ADD CONSTRAINT FK_NCL_VISOPEEMP2
	FOREIGN KEY(IDEMPRESA)
	REFERENCES NCL_EMPRESA(IDPESSOA)
;

CREATE TABLE NCL_REDEFSNH (
	ID					NUMBER(11)			NOT NULL,
	IDOPERADOR			NUMBER(11)			NOT NULL,
	DTSOLICITACAO		NUMBER(11)			NOT NULL
)
;

ALTER TABLE NCL_REDEFSNH
	ADD CONSTRAINT PK_NCL_REDEFSNH
	PRIMARY KEY (ID)
;

CREATE INDEX IDX_NCL_REDEFSNH1
	ON NCL_REDEFSNH(IDOPERADOR)
;

CREATE INDEX IDX_NCL_REDEFSNH2
	ON NCL_REDEFSNH(DTSOLICITACAO)
;
