CREATE TABLE NCL_CNFGERAL (
	NOTIFERROSREMAIL		CHAR(1)			NOT NULL,
	EMAILREMETNOTIFERROS	VARCHAR(255)		NULL,
	REMETENTEPADRAO			VARCHAR(255)		NULL,
	HABILITARSSL			CHAR(1)				NULL,
	PORTA					SMALLINT			NULL,
	REQUERAUTENTICACAO		CHAR(1)				NULL,
	SHNUSUSERVSAIDA			VARCHAR(255)		NULL,
	USUSERVSAIDA			VARCHAR(255)		NULL,
	SERVSAIDA				VARCHAR(255)		NULL,
	TIPOSERVSAIDA			CHAR(1)				NULL
)		