CREATE TABLE NCL_CNFGERAL (
	NOTIFERROSREMAIL		CHAR(1)			NOT NULL,
	EMAILREMETNOTIFERROS	VARCHAR(255)		NULL,
	REMETENTEPADRAO			VARCHAR(255)		NULL,
	HABILITARSSL			CHAR(1)				NULL,
	PORTA					SMALLINT			NULL,
	REQUERAUTENTICACAO		CHAR(1)				NULL,
	SHNUSUSERVSAIDA			VARCHAR(255)		NULL,
	USUSERVSAIDA			VARCHAR(255)		NULL,
	SERVSAIDA				VARCHAR(255)		NULL,
	TIPOSERVSAIDA			CHAR(1)				NULL
)		

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.NCL','FUN.NCL.009','Cadastro de bancos e agências');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.009','OPE.NCL.009.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.009','OPE.NCL.009.0002','Detalhar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.009','OPE.NCL.009.0003','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.009','OPE.NCL.009.0004','Excluir');	

INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.NCL','FUN.NCL.009','bogus','Nucleo/cdBancosEAgencias.aspx');