CREATE TABLE MP_TIPO_PATENTE (
	IDTIPO_PATENTE 				BIGINT 				NOT NULL,
	DESCRICAO_TIPO_PATENTE 		VARCHAR(255) 			NULL,
	SIGLA_TIPO 					CHAR(2) 				NULL,
	TEMPO_INICIO_ANOS 			INT 					NULL,
	QUANTIDADE_PAGTO 			INT					 	NULL,
	TEMPO_ENTRE_PAGTO 			INT	 					NULL,
	SEQUENCIA_INICIO_PAGTO 		INT 					NULL,
	TEM_PAGTO_INTERMEDIARIO 	CHAR(1) 			NOT NULL,
	INICIO_INTERMED_SEQUENCIA 	INT 					NULL,
	QUANTIDADE_PAGTO_INTERMED 	INT 					NULL,
	TEMPO_ENTRE_PAGTO_INTERMED 	INT						NULL,
	DESCRICAO_PAGTO 			VARCHAR(255) 			NULL,
	DESCRICAO_PAGTO_INTERMED 	VARCHAR(255) 			NULL,
	TEM_PED_EXAME 				CHAR(1) 			NOT NULL
)
;
ALTER TABLE MP_TIPO_PATENTE
	ADD CONSTRAINT PK_TIPO_PATENTE
	PRIMARY KEY(IDTIPO_PATENTE)
;