CREATE TABLE LTF_APOSTA (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	NUMCONCURSO			INTEGER			NOT NULL,
	DTCONCURSO			INTEGER			NOT NULL
)
;

ALTER TABLE LTF_APOSTA
	ADD CONSTRAINT PK_LTF_APOSTA
	PRIMARY KEY (ID)
;

CREATE INDEX IDX_LTF_APOSTA
	ON LTF_APOSTA(NOME)
;

CREATE INDEX IDX_LTF_APOSTA2
	ON LTF_APOSTA(NUMCONCURSO)
;

CREATE TABLE LTF_JOGO (
	IDAPOSTA			BIGINT			NOT NULL,
	IDJOGO				BIGINT			NOT NULL
)
;

ALTER TABLE LTF_JOGO
	ADD CONSTRAINT PK_LTF_JOGO
	PRIMARY KEY (IDAPOSTA, IDJOGO)
;

ALTER TABLE LTF_JOGO
	ADD CONSTRAINT FK_LTF_JOGO
	FOREIGN KEY(IDAPOSTA)
	REFERENCES LTF_APOSTA(ID)
;

CREATE TABLE LTF_DEZENA (
	IDAPOSTA			BIGINT			NOT NULL,
	IDJOGO				BIGINT			NOT NULL,
	INDICE				INTEGER			NOT NULL,
	DEZENAS				VARCHAR(255)	NOT NULL
)
;

ALTER TABLE LTF_DEZENA
	ADD CONSTRAINT PK_LTF_DEZENA
	PRIMARY KEY (IDAPOSTA, IDJOGO, INDICE)
;

ALTER TABLE LTF_DEZENA
	ADD CONSTRAINT FK_LTF_DEZENA1
	FOREIGN KEY(IDAPOSTA,IDJOGO)
	REFERENCES LTF_JOGO(IDAPOSTA,IDJOGO)
;