CREATE TABLE LTF_APOSTA (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	NUMCONCURSO			INTEGER			NOT NULL,
	DTCONCURSO			INTEGER			NOT NULL
)
;

ALTER TABLE LTF_APOSTA
	ADD CONSTRAINT PK_LTF_APOSTA
	PRIMARY KEY (ID)
;

CREATE INDEX IDX_LTF_APOSTA
	ON LTF_APOSTA(NOME)
;

CREATE TABLE LTF_JOGO (
	IDAPOSTA			BIGINT			NOT NULL,
	DEZENAS				VARCHAR(250)	NOT NULL,
	INDICE				INTEGER			NOT NULL
)
;

ALTER TABLE LTF_JOGO
	ADD CONSTRAINT PK_LTF_JOGO
	PRIMARY KEY (IDAPOSTA, INDICE)
;

ALTER TABLE LTF_JOGO
	ADD CONSTRAINT FK_LTF_JOGO
	FOREIGN KEY(IDAPOSTA)
	REFERENCES LTF_APOSTA(ID)
;


