ALTER TABLE FN_BOLETOS_GERADOS ADD STATUSBOLETO VARCHAR(20) NULL;

ALTER TABLE FN_BOLETOS_GERADOS ADD EHBOLETOAVULSO CHAR(1) NULL;

ALTER TABLE FN_ITEMFINANREC ADD BOLETOGERADOCOLETIVAMENTE CHAR(1) NOT NULL DEFAULT 'N';

DELETE FROM FN_BOLETOS_GERADOS;
DELETE FROM FN_ITEMFINANREC;
DELETE FROM FN_ITEMFINANRECBOLETO;
DELETE FROM MP_INTERFACEFN;

UPDATE FN_BOLETOS_GERADOS_AUX SET PROXNOSSONUMERO = 8210001001;