CREATE TABLE DRY_CONTATO (
	IDPESSOA			BIGINT			NOT NULL,
	TIPOPESSOA			SMALLINT		NOT NULL,
	CARGO				VARCHAR(255)		NULL,
	OBSERVACOES			VARCHAR(500)		NULL
)
;

ALTER TABLE DRY_CONTATO
	ADD CONSTRAINT PK_DRY_CONTATO
	PRIMARY KEY (IDPessoa)
;

ALTER TABLE DRY_CONTATO
	ADD CONSTRAINT FK_DRY_CONTATO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE DRY_SOLICAUDI (
	ID					BIGINT			NOT NULL,
	CODIGO				BIGINT			NOT NULL,
	IDCONTATO			BIGINT			NOT NULL,
	ASSUNTO				VARCHAR(255)	NOT NULL,
	DESCRICAO			VARCHAR(500)	NOT NULL,
	DATADECADASTRO		VARCHAR(20)		NOT NULL,
	ESTAATIVA			CHAR(1)			NOT NULL,
	IDUSUARIOCAD		BIGINT			NOT NULL
)
;

ALTER TABLE DRY_SOLICAUDI
	ADD CONSTRAINT PK_DRY_SOLICAUDI
	PRIMARY KEY (ID)
;

ALTER TABLE DRY_SOLICAUDI
	ADD CONSTRAINT FK_DRY_SOLICAUDI1
	FOREIGN KEY(IDCONTATO)
	REFERENCES DRY_CONTATO(IDPESSOA)
;

CREATE INDEX IDX_DRY_SOLICAUDI1
	ON DRY_SOLICAUDI(ESTAATIVA)
;

CREATE INDEX IDX_DRY_SOLICAUDI2
	ON DRY_SOLICAUDI(DATADECADASTRO)
;

CREATE INDEX IDX_DRY_SOLICAUDI3
	ON DRY_SOLICAUDI(CODIGO)
;

CREATE TABLE DRY_SOLICCONVT (
	ID					BIGINT			NOT NULL,
	CODIGO				BIGINT			NOT NULL,
	IDCONTATO			BIGINT			NOT NULL,
	DATAEHORA			VARCHAR(20)		NOT NULL,
	LOCAL				VARCHAR(500)	NOT NULL,
	DESCRICAO			VARCHAR(500)	NOT NULL,
	OBSERVACAO			VARCHAR(1000)		NULL,
	DATADECADASTRO		VARCHAR(20)		NOT NULL,
	ESTAATIVA			CHAR(1)			NOT NULL,
	IDUSUARIOCAD		BIGINT			NOT NULL
)
;

ALTER TABLE DRY_SOLICCONVT
	ADD CONSTRAINT PK_DRY_SOLICCONVT
	PRIMARY KEY (ID)
;

ALTER TABLE DRY_SOLICCONVT
	ADD CONSTRAINT FK_DRY_SOLICCONVT
	FOREIGN KEY(IDCONTATO)
	REFERENCES DRY_CONTATO(IDPESSOA)
;

CREATE INDEX IDX_DRY_SOLICCONVT1
	ON DRY_SOLICCONVT(ESTAATIVA)
;

CREATE INDEX IDX_DRY_SOLICCONVT2
	ON DRY_SOLICCONVT(DATADECADASTRO)
;

CREATE INDEX IDX_DRY_SOLICCONVT3
	ON DRY_SOLICCONVT(CODIGO)
;

CREATE INDEX IDX_DRY_SOLICCONVT4
	ON DRY_SOLICCONVT(DATAEHORA)
;