CREATE TABLE DRY_CONTATO (
	IDPESSOA			BIGINT			NOT NULL,
	TIPOPESSOA			SMALLINT		NOT NULL,
	CARGO				VARCHAR(255)		NULL,
	OBSERVACOES			VARCHAR(500)		NULL
)
;

ALTER TABLE DRY_CONTATO
	ADD CONSTRAINT PK_DRY_CONTATO
	PRIMARY KEY (IDPessoa)
;

ALTER TABLE DRY_CONTATO
	ADD CONSTRAINT FK_DRY_CONTATO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;