'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlCdPessoa

    '''<summary>
    '''ctrlCdPessoaFisica1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlCdPessoaFisica1 As Global.WorkSpace.ctrlCdPessoaFisica

    '''<summary>
    '''ctrlCdPessoaJuridica1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlCdPessoaJuridica1 As Global.WorkSpace.ctrlCdPessoaJuridica
End Class
