CREATE TABLE PET_VETERINARIO (
	IDPESSOA			NUMBER(12)		NOT NULL,
	CRMV				VARCHAR2(50)	NOT NULL,
	UF					NUMBER(5)		NOT NULL
)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT PK_PET_VETERINARIO
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT FK_PET_VETERINARIO
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE PET_ANIMAL (
	ID					NUMBER(12)		NOT NULL,
	NOME				VARCHAR2(50)	NOT NULL,
	DATADENASCIMENTO	NUMBER(9)			NULL,
	SEXO				CHAR(1)			NOT NULL,
	RACA				VARCHAR2(50)	NOT NULL,
	FOTO				VARCHAR2(255)		NULL,
	IDPROPRIETARIO		NUMBER(12)		NOT NULL,
	TIPOPESSOA			NUMBER(5)		NOT NULL,
	ESPECIE				CHAR(1)			NOT NULL
)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT PK_PET_ANIMAL
	PRIMARY KEY (ID)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT FK_PET_ANIMAL
	FOREIGN KEY(IDPROPRIETARIO)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_PET_ANIMAL
	ON PET_ANIMAL(NOME)
;