ALTER TABLE DRY_SOLICAUDI
	ADD LOCAL VARCHAR(100) DEFAULT NULL NULL
;
ALTER TABLE DRY_SOLICAUDI ALTER COLUMN ASSUNTO VARCHAR(100)
;
ALTER TABLE DRY_SOLICAUDI ALTER COLUMN DESCRICAO VARCHAR(4000)
;
ALTER TABLE DRY_SOLICCONVT ALTER COLUMN DESCRICAO VARCHAR(4000)
;
ALTER TABLE DRY_SOLICCONVT ALTER COLUMN LOCAL VARCHAR(100)
;
ALTER TABLE DRY_SOLICCONVT ALTER COLUMN OBSERVACAO VARCHAR(4000)
;