INSERT INTO NCL_MODULO (IDMODULO, NOME) VALUES ('MOD.FN','Financeiro');
	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.MP','FUN.MP.001','Contas a pagar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.001','OPE.FN.001.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.001','OPE.FN.001.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.001','OPE.FN.001.0003','Excluir');

	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.002','Gerar Boleto bancário');

	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.003','Configurações do módulo');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.018','OPE.FN.018.0001','Salvar');

INSERT INTO NCL_MENUMODULO (IDMODULO, IMAGEM) VALUES ('MOD.FN','bogus');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.001','bogus','MP/cdNaturezaPatente.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.002','bogus','MP/cdInventor.aspx','Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.003','bogus','MP/cdTipoDeProcedimentoInterno.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.004','bogus','MP/cdDespachoDeMarcas.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.005','bogus','MP/cdCadastroDeProcuradores.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.007','bogus','MP/frmProcessosDeMarcas.aspx', NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.009','bogus','MP/frmProcessosDePatentes.aspx', NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.010','bogus','MP/cdDespachoDePatentes.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.011','bogus','MP/cdPastas.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.012','bogus','MP/frmRelatorioDeProcessosDeMarcas.aspx', 'Relatórios');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.013','bogus','MP/frmRelatorioDeProcessosDeMarcasComRegistroConcedido.aspx', 'Relatórios');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.014','bogus','MP/cdTitular.aspx', 'Cadastros');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.015','bogus','MP/frmLeituraRevistaMarca.aspx', NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.016','bogus','MP/frmLeituraRevistaPatente.aspx', NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.017','bogus','MP/frmBoletoBancarioCEF.aspx', NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.MP','FUN.MP.018','bogus','MP/frmConfiguracaoDoModulo.aspx', 'Configurações');