CREATE TABLE PET_VETERINARIO (
	IDPESSOA			BIGINT			NOT NULL,
	CRMV				VARCHAR(50)		NOT NULL,
	UF					SMALLINT		NOT NULL
)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT PK_PET_VETERINARIO
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT FK_PET_VETERINARIO
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE PET_ANIMAL (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DATADENASCIMENTO	INTEGER				NULL,
	SEXO				CHAR(1)			NOT NULL,
	RACA				VARCHAR(50)		NOT NULL,
	FOTO				VARCHAR(255)		NULL,
	IDPROPRIETARIO		BIGINT			NOT NULL,
	TIPOPESSOA			SMALLINT		NOT NULL,
	ESPECIE				CHAR(1)			NOT NULL
)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT PK_PET_ANIMAL
	PRIMARY KEY (ID)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT FK_PET_ANIMAL
	FOREIGN KEY(IDPROPRIETARIO)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_PET_ANIMAL
	ON PET_ANIMAL(NOME)
;

CREATE TABLE PET_VACINA (
	ID					BIGINT			NOT NULL,
	IDANIMAL			BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DATA				INT				NOT NULL,
	OBSERVACAO			VARCHAR(4000)		NULL,
	REVACINAREM			INT					NULL,
	IDVETERINARIORESP	BIGINT			NOT NULL,
)

ALTER TABLE PET_VACINA
	ADD CONSTRAINT PK_PET_VACINA
	PRIMARY KEY (ID)
;

ALTER TABLE PET_VACINA
	ADD CONSTRAINT FK_PET_VACINA1
	FOREIGN KEY(IDANIMAL)
	REFERENCES PET_ANIMAL(ID)
;

ALTER TABLE PET_VACINA
	ADD CONSTRAINT FK_PET_VACINA2
	FOREIGN KEY(IDVETERINARIORESP)
	REFERENCES PET_VETERINARIO(IDPESSOA)
;

CREATE INDEX IDX_PET_VACINA
	ON PET_VACINA(DATA)
;

CREATE TABLE PET_VERMIFUGO (
	ID					BIGINT			NOT NULL,
	IDANIMAL			BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DATA				INT				NOT NULL,
	OBSERVACAO			VARCHAR(4000)		NULL,
	PROXDOSEEM			INT					NULL,
	IDVETERINARIORESP	BIGINT			NOT NULL,
)

ALTER TABLE PET_VERMIFUGO
	ADD CONSTRAINT PK_PET_VERMIFUGO
	PRIMARY KEY (ID)
;

ALTER TABLE PET_VERMIFUGO
	ADD CONSTRAINT FK_PET_VERMIFUGO1
	FOREIGN KEY(IDANIMAL)
	REFERENCES PET_ANIMAL(ID)
;

ALTER TABLE PET_VERMIFUGO
	ADD CONSTRAINT FK_PET_VERMIFUGO2
	FOREIGN KEY(IDVETERINARIORESP)
	REFERENCES PET_VETERINARIO(IDPESSOA)
;

CREATE INDEX IDX_PET_VERMIFUGO
	ON PET_VERMIFUGO(DATA)
;

CREATE TABLE PET_ATENDANIMAL (
	ID					BIGINT			NOT NULL,
	IDANIMAL			BIGINT			NOT NULL,
	IDVETERINARIO		BIGINT			NOT NULL,
	DATAEHORA			VARCHAR(20)		NOT NULL,
	DATAEHORARETORNO	VARCHAR(20)			NULL,
	QUEIXA				VARCHAR(4000)		NULL,
	SINCLINICO			VARCHAR(4000)		NULL,
	PROGNOSTICO			VARCHAR(4000)		NULL,
	TRATAMENTO			VARCHAR(4000)		NULL,
	PESODOANIMAL		FLOAT				NULL
);

ALTER TABLE PET_ATENDANIMAL
	ADD CONSTRAINT PK_PET_ATENDANIMAL
	PRIMARY KEY (ID)
;

ALTER TABLE PET_ATENDANIMAL
	ADD CONSTRAINT FK_PET_ATENDANIMAL1
	FOREIGN KEY(IDANIMAL)
	REFERENCES PET_ANIMAL(ID)
;

ALTER TABLE PET_ATENDANIMAL
	ADD CONSTRAINT FK_PET_ATENDANIMAL2
	FOREIGN KEY(IDVETERINARIO)
	REFERENCES PET_VETERINARIO(IDPESSOA)
;

CREATE INDEX IDX_PET_ATENDANIMAL
	ON PET_ATENDANIMAL(DATAEHORA)
;

CREATE TABLE PET_ATENDVAC (
	IDATENDIMENTO		BIGINT		NOT NULL,
	IDVACINA			BIGINT		NOT NULL
);

ALTER TABLE PET_ATENDVAC
	ADD CONSTRAINT PK_PET_ATENDVAC
	PRIMARY KEY (IDATENDIMENTO, IDVACINA)
;

ALTER TABLE PET_ATENDVAC
	ADD CONSTRAINT FK_PET_ATENDVAC1
	FOREIGN KEY(IDATENDIMENTO)
	REFERENCES PET_ATENDANIMAL(ID)
;

ALTER TABLE PET_ATENDVAC
	ADD CONSTRAINT FK_PET_ATENDVAC2
	FOREIGN KEY(IDVACINA)
	REFERENCES PET_VACINA(ID)
;

CREATE TABLE PET_ATENDVERM (
	IDATENDIMENTO		BIGINT		NOT NULL,
	IDVERMIFUGO			BIGINT		NOT NULL
);

ALTER TABLE PET_ATENDVERM
	ADD CONSTRAINT PK_PET_ATENDVERM
	PRIMARY KEY (IDATENDIMENTO, IDVERMIFUGO)
;

ALTER TABLE PET_ATENDVERM
	ADD CONSTRAINT FK_PET_ATENDVERM1
	FOREIGN KEY(IDATENDIMENTO)
	REFERENCES PET_ATENDANIMAL(ID)
;

ALTER TABLE PET_ATENDVERM
	ADD CONSTRAINT FK_PET_ATENDVERM2
	FOREIGN KEY(IDVERMIFUGO)
	REFERENCES PET_VERMIFUGO(ID)
;