DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA='FUN.NCL.004';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA ='OPE.NCL.004.0001';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA='FUN.NCL.009';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA ='OPE.NCL.009.0001';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA ='OPE.NCL.009.0002';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA ='OPE.NCL.009.0003';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA='FUN.NCL.011';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA ='OPE.NCL.011.0001';

DELETE FROM NCL_ATALHO WHERE ID='FUN.NCL.004';
DELETE FROM NCL_ATALHO WHERE ID='FUN.NCL.009';
DELETE FROM NCL_ATALHO WHERE ID='FUN.NCL.011';

DELETE FROM NCL_MENUFUNCAO WHERE IDMODULO='MOD.NCL' AND IDFUNCAO='FUN.NCL.004';
DELETE FROM NCL_OPERACAO WHERE IDMODULO = 'MOD.NCL' AND IDFUNCAO='FUN.NCL.004';
DELETE FROM NCL_FUNCAO WHERE IDMODULO='MOD.NCL' AND IDFUNCAO='FUN.NCL.004';

DELETE FROM NCL_MENUFUNCAO WHERE IDMODULO='MOD.NCL' AND IDFUNCAO='FUN.NCL.009';
DELETE FROM NCL_OPERACAO WHERE IDMODULO = 'MOD.NCL' AND IDFUNCAO='FUN.NCL.009';
DELETE FROM NCL_FUNCAO WHERE IDMODULO='MOD.NCL' AND IDFUNCAO='FUN.NCL.009';

DELETE FROM NCL_MENUFUNCAO WHERE IDMODULO='MOD.NCL' AND IDFUNCAO='FUN.NCL.011';
DELETE FROM NCL_OPERACAO WHERE IDMODULO = 'MOD.NCL' AND IDFUNCAO='FUN.NCL.011';
DELETE FROM NCL_FUNCAO WHERE IDMODULO='MOD.NCL' AND IDFUNCAO='FUN.NCL.011';

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.NCL','FUN.NCL.004','Alterar senha de operadores');
INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.NCL','FUN.NCL.004','bogus','Nucleo/frmAlterarSenhaDoOperador.aspx');

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.NCL','FUN.NCL.011','Configurações pessoais');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.011','OPE.NCL.011.0001','Atalhos');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.011','OPE.NCL.011.0002','Temas');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.011','OPE.NCL.011.0003','Papel de parede');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.011','OPE.NCL.011.0004','Agenda');			
INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.NCL','FUN.NCL.011','bogus','Nucleo/frmConfiguracoesPessoais.aspx');		

ALTER TABLE NCL_AGENDA ADD IDPESSOAPADRAO BIGINT DEFAULT 50002 NOT NULL;

ALTER TABLE NCL_AGENDA
	ADD CONSTRAINT FK_NCL_AGENDA2
	FOREIGN KEY(IDPESSOAPADRAO)
	REFERENCES NCL_PESSOA(ID)
;
