CREATE TABLE PET_VETERINARIO (
	IDPESSOA			BIGINT			NOT NULL,
	CRMV				VARCHAR(50)		NOT NULL,
	UF					SMALLINT		NOT NULL
)ENGINE=InnoDB
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT PK_PET_VETERINARIO
	PRIMARY KEY (IDPESSOA)
;

ALTER TABLE PET_VETERINARIO
	ADD CONSTRAINT FK_PET_VETERINARIO
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE PET_ANIMAL (
	ID					BIGINT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DATADENASCIMENTO	INTEGER				NULL,
	SEXO				CHAR(1)			NOT NULL,
	RACA				VARCHAR(50)		NOT NULL,
	FOTO				VARCHAR(255)		NULL,
	IDPROPRIETARIO		BIGINT			NOT NULL,
	TIPOPESSOA			SMALLINT		NOT NULL,
	ESPECIE				CHAR(1)			NOT NULL
)ENGINE=InnoDB
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT PK_PET_ANIMAL
	PRIMARY KEY (ID)
;

ALTER TABLE PET_ANIMAL
	ADD CONSTRAINT FK_PET_ANIMAL
	FOREIGN KEY(IDPROPRIETARIO)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_PET_ANIMAL
	ON PET_ANIMAL(NOME)
;
