CREATE TABLE NCL_LEMBRETE (
	ID					BIGINT			NOT NULL,
	IDPESSOA			BIGINT			NOT NULL,
	INICIO				VARCHAR(20)		NOT NULL,
	FIM					VARCHAR(20)		NOT NULL,
	ASSUNTO				VARCHAR(50)		NOT NULL,
	LOCAL				VARCHAR(100)		NULL,
	DESCRICAO			VARCHAR(4000)		NULL,
	STATUS				CHAR(1)			NOT NULL
)
;

ALTER TABLE NCL_LEMBRETE
	ADD CONSTRAINT PK_NCL_LEMBRETE
	PRIMARY KEY (ID)
;

ALTER TABLE NCL_LEMBRETE
	ADD CONSTRAINT FK_NCL_LEMBRETE1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_NCL_LEMBRETE1
	ON NCL_LEMBRETE(INICIO)
;

CREATE INDEX IDX_NCL_LEMBRETE2
	ON NCL_LEMBRETE(FIM)
;

ALTER TABLE NCL_TAREFA
	ADD STATUS CHAR(1) DEFAULT 'E' NOT NULL
;

ALTER TABLE NCL_COMPROMISSO
	ADD STATUS CHAR(1) DEFAULT 'P' NOT NULL
;

INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0010','Inserir lembrete');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0011','Remover lembrete');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0012','Modificar lembrete');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0013','Imprimir lembretes');