CREATE TABLE NCL_IDENTIFICADOR (
	NUMHIGH				INTEGER			NOT NULL
)
;

CREATE TABLE NCL_MUNICIPIO (
	ID					FLOAT			NOT NULL,
	NOME				VARCHAR(30)		NOT NULL,
	UF					INTEGER			NOT NULL,
	CEP					FLOAT				NULL,
	PRIMARY KEY (ID)
)
;

CREATE INDEX IDX_NCL_MUNICIPIO1
	ON NCL_MUNICIPIO(NOME)
;

CREATE TABLE NCL_GRUPO (
	ID					FLOAT			NOT NULL,
	NOME				VARCHAR(30)		NOT NULL,
	STATUS				CHAR(1)			NOT NULL,
	PRIMARY KEY (ID)
)
;

CREATE INDEX IDX_NCL_GRUPO1
	ON NCL_GRUPO(NOME)
;

CREATE TABLE NCL_MODULO (
	IDMODULO			VARCHAR(7)		NOT NULL,
	NOME				VARCHAR(30)		NOT NULL,
	PRIMARY KEY(IDMODULO)
)
;

CREATE TABLE NCL_FUNCAO (
	IDMODULO			VARCHAR(7)		NOT NULL,
	IDFUNCAO			VARCHAR(11)		NOT NULL,
	NOME				VARCHAR(100)	NOT NULL,
	PRIMARY KEY(IDMODULO, IDFUNCAO),
	FOREIGN KEY(IDMODULO) REFERENCES NCL_MODULO(IDMODULO)
)
;

CREATE TABLE NCL_OPERACAO (
	IDMODULO			VARCHAR(7)		NOT NULL,
	IDFUNCAO			VARCHAR(11)		NOT NULL,
	IDOPERACAO			VARCHAR(16)		NOT NULL,
	NOME				VARCHAR(30)		NOT NULL,
	PRIMARY KEY (IDMODULO, IDFUNCAO, IDOPERACAO), 
	FOREIGN KEY(IDMODULO, IDFUNCAO) REFERENCES NCL_FUNCAO(IDMODULO,IDFUNCAO)
)
;

CREATE TABLE NCL_MENUMODULO (
	IDMODULO			VARCHAR(7)		NOT NULL,
	IMAGEM				VARCHAR(255)	NOT NULL,
	PRIMARY KEY (IDMODULO),
	FOREIGN KEY(IDMODULO) REFERENCES NCL_MODULO(IDMODULO)
)
;

CREATE TABLE NCL_MENUFUNCAO (
	IDMODULO			VARCHAR(7)		NOT NULL,
	IDFUNCAO			VARCHAR(11)		NOT NULL,
	IMAGEM				VARCHAR(100)	NOT NULL,
	URL					VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IDMODULO,IDFUNCAO), 
	FOREIGN KEY(IDMODULO, IDFUNCAO)	REFERENCES NCL_FUNCAO(IDMODULO, IDFUNCAO)
)
;

CREATE TABLE NCL_AUTORIZACAO (
	IDGRUPO				FLOAT			NOT NULL,
	IDDIRETIVA			VARCHAR(20)		NOT NULL,
	PRIMARY KEY(IDGRUPO, IDDIRETIVA),
	FOREIGN KEY(IDGRUPO) REFERENCES NCL_GRUPO(ID)
)
;

CREATE TABLE NCL_PESSOA (
	ID					FLOAT			NOT NULL,
	NOME				VARCHAR(100)	NOT NULL,
	TIPO				INTEGER			NOT NULL,
	ENDEMAIL			VARCHAR(255)		NULL,
	LOGRADOURO			VARCHAR(255)		NULL,
	COMPLEMENTO			VARCHAR(255)		NULL,
	IDMUNICIPIO			FLOAT				NULL,
	CEP					FLOAT				NULL,
	BAIRRO				VARCHAR(100)		NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(IDMUNICIPIO) REFERENCES NCL_MUNICIPIO(ID)
)
;

CREATE INDEX IDX_NCL_PESSOA1
	ON NCL_PESSOA(NOME)
;

CREATE TABLE NCL_PESSOAFISICA (
	IDPESSOA			FLOAT			NOT NULL,
	DATANASCIMENTO		INTEGER			NOT NULL,
	ESTADOCIVIL			CHAR(1)			NOT NULL,
	NACIONALIDADE		CHAR(1)				NULL,
	RACA				CHAR(1)				NULL,
	SEXO				CHAR(1)			NOT NULL,
	NOMEMAE				VARCHAR(100)	NOT NULL,
	NOMEPAI				VARCHAR(100)		NULL,
	NUMERORG			VARCHAR(30)			NULL,
	ORGEXPEDITOR		VARCHAR(20)			NULL,
	DATAEXP				INTEGER				NULL,
	UFEXP				INTEGER				NULL,
	CPF					CHAR(11)			NULL,
	NATURALIDADE		FLOAT			NOT NULL,
	FOTO				VARCHAR(100)		NULL,
	PRIMARY KEY (IDPESSOA), 
	FOREIGN KEY(IDPESSOA)  REFERENCES NCL_PESSOA(ID)
)
;

CREATE TABLE NCL_PESSOAJURIDICA (
	IDPESSOA			FLOAT			NOT NULL,
	NOMEFANTASIA		VARCHAR(100)		NULL,
	CNPJ				CHAR(14)		NOT	NULL,
	IE					VARCHAR(14)			NULL,
	IM					VARCHAR(20)			NULL,
	PRIMARY KEY (IDPESSOA),
	FOREIGN KEY(IDPESSOA) REFERENCES NCL_PESSOA(ID)
)
;

CREATE TABLE NCL_OPERADOR (
	IDPESSOA			FLOAT			NOT NULL,
	TIPOPESSOA			INTEGER			NOT NULL,
	LOGIN				VARCHAR(255)	NOT NULL,
	STATUS				CHAR(1)			NOT NULL,
	PRIMARY KEY (IDPessoa), 
	FOREIGN KEY(IDPESSOA) REFERENCES NCL_PESSOA(ID)
)
;

CREATE INDEX IDX_NCL_OPERADOR1
	ON NCL_OPERADOR(LOGIN)
;

CREATE TABLE NCL_PERFIL (
	IDUSUARIO			FLOAT			NOT NULL,
	IMAGEMDESKTOP		VARCHAR(100)	NOT NULL,
	TEMA				VARCHAR(20)		NOT NULL,
	PRIMARY KEY (IDUSUARIO), 
	FOREIGN KEY(IDUSUARIO) REFERENCES NCL_OPERADOR(IDPESSOA)
)
;

CREATE TABLE NCL_GRPOPE (
	IDOPERADOR			FLOAT			NOT NULL,
	IDGRUPO				FLOAT			NOT NULL,
	PRIMARY KEY (IDOPERADOR,IDGRUPO),
	FOREIGN KEY(IDOPERADOR)	REFERENCES NCL_OPERADOR(IDPESSOA),
	FOREIGN KEY(IDGRUPO) REFERENCES NCL_GRUPO(ID)
)
;

CREATE TABLE NCL_SNHOP (
	IDOPERADOR			FLOAT			NOT NULL,
	SENHA				VARCHAR(255)	NOT NULL,
	DATACADASTRO		FLOAT			NOT NULL,
	PRIMARY KEY (IDOPERADOR),
	FOREIGN KEY(IDOPERADOR)	REFERENCES NCL_OPERADOR(IDPESSOA)
)
;

CREATE TABLE NCL_CLIENTE (
	IDPESSOA			FLOAT			NOT NULL,
	TIPOPESSOA			INTEGER			NOT NULL,
	PRIMARY KEY (IDPessoa),
	FOREIGN KEY(IDPESSOA) REFERENCES NCL_PESSOA(ID)
)
;

CREATE TABLE NCL_CFGAGENDA (
	ID					FLOAT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	PRIMEIRODIASEMANA	INTEGER			NOT NULL,
	HORARIOINICIO		INTEGER			NOT NULL,
	HORARIOFIM			INTEGER			NOT NULL,
	INTERVALO			INTEGER			NOT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX IDX_NCL_CFGAGENDA
	ON NCL_CFGAGENDA(NOME)
;

CREATE TABLE NCL_ATALHO (
	ID					VARCHAR(100)	NOT NULL,
	NOME				VARCHAR(100)	NOT NULL,
	TIPO				CHAR(1)			NOT NULL,
	URL					VARCHAR(100)	NOT NULL,
	IMAGEM				VARCHAR(50)		NOT NULL,
	IDUSUARIO			FLOAT			NOT NULL,
	PRIMARY KEY (ID,IDUSUARIO)
)
;

CREATE INDEX IDX_NCL_ATALHO
	ON NCL_ATALHO(IDUSUARIO)
;