ALTER TABLE NCL_COMPROMISSO ALTER COLUMN ASSUNTO VARCHAR(4000);
ALTER TABLE NCL_COMPROMISSO ALTER COLUMN LOCAL VARCHAR(4000);
ALTER TABLE NCL_COMPROMISSO ALTER COLUMN DESCRICAO VARCHAR(4000);
ALTER TABLE NCL_LEMBRETE ALTER COLUMN ASSUNTO VARCHAR(4000);
ALTER TABLE NCL_LEMBRETE ALTER COLUMN LOCAL VARCHAR(4000);
ALTER TABLE NCL_LEMBRETE ALTER COLUMN DESCRICAO VARCHAR(4000);
ALTER TABLE NCL_TAREFA ALTER COLUMN ASSUNTO VARCHAR(4000);
ALTER TABLE NCL_TAREFA ALTER COLUMN DESCRICAO VARCHAR(4000);
EXEC sp_rename 'NCL_AGENDA', 'NCL_CNFAGENDAUSU';

DELETE FROM NCL_OPERACAO WHERE IDFUNCAO ='FUN.NCL.012';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA LIKE 'OPE.NCL.012%'
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0001','Inserir compromisso');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0002','Remover compromisso');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0003','Modificar compromisso');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0004','Inserir tarefa');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0005','Remover tarefa');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0006','Modificar tarefa');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0007','Visualizar outras agendas');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0008','Inserir lembrete');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0009','Remover lembrete');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0010','Modificar lembrete');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.NCL','FUN.NCL.012','OPE.NCL.012.0011','Imprmir agenda');

BEGIN 
	DECLARE CursorGrupos CURSOR FOR SELECT ID FROM NCL_GRUPO WHERE STATUS = 'A'																
	DECLARE @IdGrupo BIGINT
  
  	BEGIN TRANSACTION
  		OPEN CursorGrupos
	  
    FETCH NEXT FROM CursorGrupos INTO @IdGrupo
	
    WHILE @@FETCH_STATUS = 0
		BEGIN    
		
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0001');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0002');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0003');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0004');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0005');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0006');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0007');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0008');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0009');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0010');
		INSERT INTO NCL_AUTORIZACAO VALUES (@IdGrupo, 'OPE.NCL.012.0011');

		FETCH NEXT FROM CursorGrupos INTO @IdGrupo
		
		END
		
    CLOSE CursorGrupos
	DEALLOCATE CursorGrupos
	COMMIT TRANSACTION
END;