ALTER TABLE NCL_COMPROMISSO ALTER COLUMN ASSUNTO VARCHAR(4000);
ALTER TABLE NCL_COMPROMISSO ALTER COLUMN LOCAL VARCHAR(4000);
ALTER TABLE NCL_COMPROMISSO ALTER COLUMN DESCRICAO VARCHAR(4000);
ALTER TABLE NCL_LEMBRETE ALTER COLUMN ASSUNTO VARCHAR(4000);
ALTER TABLE NCL_LEMBRETE ALTER COLUMN LOCAL VARCHAR(4000);
ALTER TABLE NCL_LEMBRETE ALTER COLUMN DESCRICAO VARCHAR(4000);
ALTER TABLE NCL_TAREFA ALTER COLUMN ASSUNTO VARCHAR(4000);
ALTER TABLE NCL_TAREFA ALTER COLUMN DESCRICAO VARCHAR(4000);
