CREATE TABLE DRY_SOLICVISI (
	ID					BIGINT			NOT NULL,
	CODIGO				BIGINT			NOT NULL,
	IDCONTATO			BIGINT			NOT NULL,
	ASSUNTO				VARCHAR(2000)	NOT NULL,
	DESCRICAO			VARCHAR(4000)	NOT NULL,
	DATADECADASTRO		VARCHAR(20)		NOT NULL,
	ESTAATIVA			CHAR(1)			NOT NULL,
	IDUSUARIOCAD		BIGINT			NOT NULL,
	LOCAL				VARCHAR(100)		NULL
)
;

ALTER TABLE DRY_SOLICVISI
	ADD CONSTRAINT PK_DRY_SOLICVISI
	PRIMARY KEY (ID)
;

ALTER TABLE DRY_SOLICVISI
	ADD CONSTRAINT FK_DRY_SOLICVISI1
	FOREIGN KEY(IDCONTATO)
	REFERENCES DRY_CONTATO(IDPESSOA)
;

CREATE INDEX IDX_DRY_SOLICVISI1
	ON DRY_SOLICVISI(ESTAATIVA)
;

CREATE INDEX IDX_DRY_SOLICVISI2
	ON DRY_SOLICVISI(DATADECADASTRO)
;

CREATE INDEX IDX_DRY_SOLICVISI3
	ON DRY_SOLICVISI(CODIGO)
;

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','Solicitações de visita');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','OPE.DRY.004.0001','Inserir');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','OPE.DRY.004.0002','Modificar');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','OPE.DRY.004.0003','Excluir');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','OPE.DRY.004.0004','Despachar');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','OPE.DRY.004.0005','Finalizar');
INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.004','OPE.DRY.004.0006','Imprimir');

INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.DRY','FUN.DRY.004','bogus','Diary/frmSolicitacoesDeVisita.aspx');