CREATE TABLE MP_TIPO_PATENTE (
	IDTIPO_PATENTE 				NUMBER(11) 				NOT NULL,
	DESCRICAO_TIPO_PATENTE 		VARCHAR2(255) 			NOT	NULL,
	SIGLA_TIPO 					CHAR(2) 				NOT	NULL,
	TEMPO_INICIO_ANOS 			NUMBER(9) 				NOT	NULL,
	QUANTIDADE_PAGTO 			NUMBER(9) 				NOT	NULL,
	TEMPO_ENTRE_PAGTO 			NUMBER(9) 	 			NOT	NULL,
	SEQUENCIA_INICIO_PAGTO 		NUMBER(9)  				NOT	NULL,
	TEM_PAGTO_INTERMEDIARIO 	CHAR(1) 				    NULL,
	INICIO_INTERMED_SEQUENCIA 	NUMBER(9)  				NOT	NULL,
	QUANTIDADE_PAGTO_INTERMED 	NUMBER(9)  				NOT	NULL,
	TEMPO_ENTRE_PAGTO_INTERMED 	NUMBER(9) 				NOT	NULL,
	DESCRICAO_PAGTO 			VARCHAR2(255) 			NOT	NULL,
	DESCRICAO_PAGTO_INTERMED 	VARCHAR2(255) 			NOT	NULL,
	TEM_PED_EXAME 				CHAR(1) 				    NULL
)
;
ALTER TABLE MP_TIPO_PATENTE
	ADD CONSTRAINT PK_TIPO_PATENTE
	PRIMARY KEY(IDTIPO_PATENTE, DESCRICAO_TIPO_PATENTE, SIGLA_TIPO)
;


CREATE TABLE MP_INVENTOR (
	IDPESSOA					NUMBER(11)				NOT NULL,
	TIPOPESSOA					NUMBER(5)				NOT NULL,
	DTCADASTRO					NUMBER(5)				NOT NULL,
	INFOADICIONAL				VARCHAR2(4000)				NULL
);

ALTER TABLE MP_INVENTOR
	ADD CONSTRAINT PK_MP_INVENTOR
	PRIMARY KEY (IDPessoa)
;

ALTER TABLE MP_INVENTOR
	ADD CONSTRAINT FK_MP_INVENTOR1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE TABLE MP_TIPO_ANDAMENTO_INTERNO(
	IDTIPO_ANDAMENTO_INTERNO NUMBER(11) NOT NULL,
	DESCRICAO_TIPO varchar(255) NOT NULL
	);
	
	ALTER TABLE MP_TIPO_ANDAMENTO_INTERNO
	ADD CONSTRAINT PK_TIPO_ANDAMENTO_INTERNO
	PRIMARY KEY(IDTIPO_ANDAMENTO_INTERNO);