INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(10, 'TELE NORTE LESTE PARTICIPACOES S/A', 20120630, 19991109, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 146, 0, 0, 0, 'TELEMAR MATRIZ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(11, 'TELEMAR NORTE LESTE SA', 20120630, 19991109, 0, 0, 11, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 164, 0, 0, 0, 'TELEMAR RIO DE JANEIRO', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(999, 'TELEMAR PARTICIPACOES S/A', 20120630, 20000420, 0, 0, 0, 0, 5, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR PARTICIPACOES S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(1, 'TELE NORTE LESTE PARTICIPAÇÕES S.A', 19990831, 0, 0, 0, 21959, 21959, 0, 'N', 0, 'N', 'S', 2, 0, 0, 4400476, 75310, 0, 0, 0, 'TNL', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(13, 'TELEMAR NORTE LESTE SA  ES', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR ESPIRITO SANTO', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(14, 'TELEMAR NORTE LESTE SA  BA', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR BAHIA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(15, 'TELEMAR NORTE LESTE SA  SE', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR SERGIPE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(16, 'TELEMAR NORTE LESTE SA  AL', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR ALAGOAS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(17, 'TELEMAR NORTE LESTE SA  PE', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR PERNAMBUCO', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(19, 'TELEMAR NORTE LESTE SA  RN', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR RIO GRANDE DO NORTE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(18, 'TELEMAR NORTE LESTE SA  PB', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR PARAIBA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(20, 'TELEMAR NORTE LESTE SA  CE', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR CEARA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(21, 'TELEMAR NORTE LESTE SA  PI', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR PIAUI', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(22, 'TELEMAR NORTE LESTE SA  MA', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR MARANHAO', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(23, 'TELEMAR NORTE LESTE SA  PA', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR PARA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(24, 'TELEMAR NORTE LESTE SA  AM', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR AMAZONAS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(25, 'TELEMAR NORTE LESTE SA  AP', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR AMAPA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(26, 'TELEMAR NORTE LESTE SA  RR', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR RORAIMA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(12, 'TELEMAR NORTE LESTE SA  MG', 20120630, 19991110, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 134, 0, 0, 0, 'TELEMAR MINAS GERAIS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(998, 'TELE NORTE LESTE PARTICIPACOES S/A.', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TNL', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(997, 'TELEMAR NORTE LESTE S/A    MG', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TMG', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(996, 'TELEMAR NORTE LESTE S/A    ES', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TES', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(995, 'TELEMAR NORTE LESTE S/A    PE', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TPE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(994, 'TELEMAR NORTE LESTE S/A    RN', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TRN', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(993, 'TELEMAR NORTE LESTE S/A    PB', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TPB', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(992, 'TELEMAR NORTE LESTE S/A    BA', 20120630, 20000420, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 21, 0, 0, 0, 'TELEMAR CONSELHEIROS - TBA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(991, 'TELEMAR NORTE LESTE S/A    SE', 20120630, 20000718, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 8, 0, 0, 0, 'TELEMAR CONSELHEIROS - TSE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(990, 'TELEMAR NORTE LESTE S/A    AL', 20120630, 20000718, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 8, 0, 0, 0, 'TELEMAR CONSELHEIROS - TAL', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(989, 'TELEMAR NORTE LESTE S/A', 20120630, 20000920, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR  CONSELHEIROS - TRJ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(982, 'TELEMAR NORTE LESTE S/A    CE', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TCE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(983, 'TELEMAR NORTE LESTE S/A    PI', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TPI', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(984, 'TELEMAR NORTE LESTE S/A    MA', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TMA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(985, 'TELEMAR NORTE LESTE S/A    PA', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TPA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(986, 'TELEMAR NORTE LESTE S/A    AM', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TAM', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(987, 'TELEMAR NORTE LESTE S/A    AP', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TAP', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(988, 'TELEMAR NORTE LESTE S/A    RR', 20120630, 20001122, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 5, 0, 0, 0, 'TELEMAR CONSELHEIROS - TRR', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(71, 'HICORP COMUNICAÇÕES CORPORAT', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 4, 0, 0, 0, ' ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(91, 'TNL PCS S/A', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 3, 0, 0, 0, 'PCS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(45, 'TELEMAR ACESSO', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 0, 0, 0, 0, ' ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(810, 'TELE NORTE LESTE PARTICIPACOES S/A-ESTAG', 20120630, 19991109, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 137, 0, 0, 0, 'TELEMAR MATRIZ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(95, 'TNL PCS PARTICIPAÇÕES SA', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(811, 'TELEMAR NORTE LESTE SA-ESTAG', 20120630, 19991109, 0, 0, 1, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 138, 0, 0, 0, 'TELEMAR RIO DE JANEIRO', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(861, 'TNEXT S/A-ESTAG', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 5, 0, 0, 0, 'TNEXT', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(871, 'HICORP COMUNICAÇÕES CORPORAT-ESTAG', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 4, 0, 0, 0, ' ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(891, 'TNL PCS S/A-ESTAG', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 3, 0, 0, 0, 'PCS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(881, 'CONTAX S/A-ESTAG', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 1, 0, 0, 0, ' ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(46, 'PEGASUS TELECOM S.A.', 20120630, 0, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'PEGASUS TELECOM S.A.', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(846, 'TELEMAR PEGASUS - ESTAG', 20120630, 20030318, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(49, 'ORBITALL (MIGRACAO INOVACAO)', 20120630, 20040604, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'ORBITALL (MIGRACAO INOVACAO)', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(44, 'TELEMAR INTERNET LTDA', 20120630, 20050217, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 0, 0, 0, 0, 'ABS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(198, 'TELEMAR - APOSENTADOS', 20120630, 20060508, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'TELEMAR APOSENTADOS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(197, 'TELEMAR ACT CONTINUIDADE PLANO DE SAUDE', 20120630, 20060925, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(62, 'SEREDE - SERVIÇOS DE REDE S.A.', 20120630, 20070718, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'SEREDE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(66, 'WAY TV BELO HORIZONTE S/A', 20120630, 20080109, 0, 0, 0, 0, 0, 'N', 0, 'N', 'N', 2, 0, 0, 0, 0, 0, 0, 0, 'WAY TV', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(40, 'AMAZONIA CELULAR S.A.', 20120630, 20080626, 0, 0, 445, 445, 0, 'N', 0, 'S', 'S', 2, 0, 0, 0, 1259, 0, 0, 0, 'AMAZONIA CELULAR S.A.', 0, 0, 0, 'N', 40, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(2, 'AMAZONIA CELULAR S/A - PARA (MIGRAÇÃO)', 20120630, 20080626, 0, 0, 0, 0, 0, 'N', 0, 'S', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'AMAZONIA CELULAR S/A - PARA (MIGRAÇÃO)', 0, 0, 0, 'N', 2, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(3, 'AMAZONIA CELULAR S/A - AMAZONAS (MIGRAÇÃO)', 20120630, 20080626, 0, 0, 0, 0, 0, 'N', 0, 'S', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'AMAZONIA CELULAR S/A - AMAZONAS (MIGRAÇÃO)', 0, 0, 0, 'N', 3, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(5, 'AMAZONIA CELULAR S/A - AMAPA (MIGRAÇÃO)', 20120630, 20080626, 0, 0, 0, 0, 0, 'N', 0, 'S', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'AMAZONIA CELULAR S/A - AMAPA (MIGRAÇÃO)', 0, 0, 0, 'N', 5, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(6, 'AMAZONIA CELULAR S/A - RORAIMA (MIGRAÇÃO)', 20120630, 20080626, 0, 0, 0, 0, 0, 'N', 0, 'S', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'AMAZONIA CELULAR S/A - RORAIMA (MIGRAÇÃO)', 0, 0, 0, 'N', 6, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(41, 'TAB EVENTOS EMP04 AMAZONIA CELULAR', 20080526, 20080526, 0, 0, 0, 0, 0, 'N', 0, 'S', 0, 1, 0, 0, 0, 3, 0, 0, 0, 'TABELA EVENTOS', 0, 0, 0, 'N', 41, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(70, 'PAGGO ADM DE CREDITO LTDA', 20120630, 20080909, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'PGA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(72, 'PAGGO EMPREENDIMENTOS S/A', 20120630, 20080909, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'PGE', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(74, 'PAGGO ACQUIRER GESTAO MEIOS DE PAGAM', 20120630, 20080909, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'PGQ', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(7, 'TELENORTE PARTICIPACOES S/A', 20120630, 20080912, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'TELENORTE PARTICIPACOES', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(102, 'OI S/A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'OI S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(103, 'BRT SERV DE INTERNET', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'BRT SERV DE INTERNET', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(104, '14 BRASIL TELECOM CELULAR S/A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, '14 BRASIL TELECOM CELULAR S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(105, 'IBEST S/A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'IBEST S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(106, 'BRASIL TELECOM COM MULT LTDA', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'BRASIL TELECOM COM MULT LTDA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(107, 'VANT TELECOMUNICAÇÕES S/A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'VANT TELECOMUNICAÇÕES S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(108, 'FREELANCE S.A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'FREELANCE S.A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(109, 'BRASIL TELECOM CABOS SUBM LTDA', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'BRASIL TELECOM CABOS SUBM LTDA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(115, 'INTERNET GROUP DO BRASIL S/A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'INTERNET GROUP DO BRASIL S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(503, 'BRT DESLIGADOS COM BENEFICIO', 20120630, 20090430, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'BENEICIOS BRT', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(502, 'OI S/A - APOSENTADOS', 20120630, 20090331, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'OI S/A JURIDICO/APOSENTADOS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(310, 'GLOBENET INTERN', 20120630, 20090722, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'GLOBENET', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(101, 'BRASIL TELECOM PARTICIP S/A', 20120630, 20090212, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'BRASIL TELECOM PARTICIP S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(112, 'BRASIL TELECOM CALL CENTER S/A', 20120630, 20090505, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'CALL CENTER BRT', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(199, 'OPINIA S/A', 20120630, 20090707, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'OPINIA S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(901, 'BRASIL TELECOM PARTICIP SA', 20120630, 20090724, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'BRASIL TELECOM PARTICIP SA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(902, 'OI S/A CONSELHO', 20120630, 20090724, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'OI S/A CONSELHO', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(84, 'COARI PARTICIPACOES S/A', 20120630, 20091111, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'COARI PARTICIP S/A', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(75, 'PAGGO ADMINISTRADORA DE CREDITO LTDA', 20120630, 20100106, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'PAGGO ADMINISTRADORA', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(99, 'GLOBENET INTERNACIONAL', 20120630, 20100208, 0, 0, 0, 0, 0, 'N', 0, 'N', 0, 1, 0, 0, 0, 0, 0, 0, 0, 'GLOBENET', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(52, 'DOMMO EMPREEND IMOBILIARIOS SA', 20120630, 20100312, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'TCAS', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(73, 'COPART 4  PARTICIPACOES SA', 20120630, 20100722, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'TCO4', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(116, 'COPART 5  PARTICIPACOES SA', 20120630, 20100723, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(743, 'PAGGO SOLUCOES E MEIOS DE PAGAMENTO SA', 20120630, 20101123, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'PAGGO SOLUCOES', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(96, 'TELE NORTELESTE PARTICIPACOES S/A', 20120630, 20111123, 0, 0, 0, 0, 0, 'N', 0, 'N', 'S', 2, 0, 0, 0, 0, 0, 0, 0, 'TLM ESTRANG', 0, 0, 0, 'N', 1, 'N', 0)
GO

INSERT INTO EMPRESAS (EMCODEMP, EMNOMEMP, EMDTREFER, EMDTINSTAL, EMDTVENCDM, EMDTFECH, EMDTMDFORM, EMDTORDEN, EMNUMFUNCS, EMINDTBSAL, EMNIVTBSAL, EMINDTBPRO, EMINDFGTSC, EMCODCLASS, EMCODBCODP, EMCODAGEDP, EMNUMSERIE, EMDTULTMOD, EMNUMMAXFU, EMNUMMAXEM, EMTIPVISIB, EMNOMFANT, EMNUMCAGED, EMNREXPSEN, EMCONTRUPD, EMINDSIMPLES, EMCODEMPGEN, EMINDTERC, EMTERCEMPPRI)VALUES(100, 'EMPRESA PARA VALIDACAO DO POP DE IMPLANTACAO', 20120229, 20081205, 0, 0, 0, 0, 0, 'N', 0, 'S', ' ', 1, 0, 0, 0, 0, 0, 0, ' ', 0, 0, 0, 0, ' ', 100, 'N', 0)
GO

