CREATE TABLE MP_TIPO_PATENTE (
	IDTIPO_PATENTE 				NUMBER(11) 				NOT NULL,
	DESCRICAO_TIPO_PATENTE 		VARCHAR2(255) 				NULL,
	SIGLA_TIPO 					CHAR(2) 					NULL,
	TEMPO_INICIO_ANOS 			NUMBER(9) 					NULL,
	QUANTIDADE_PAGTO 			NUMBER(9) 					NULL,
	TEMPO_ENTRE_PAGTO 			NUMBER(9) 	 				NULL,
	SEQUENCIA_INICIO_PAGTO 		NUMBER(9)  					NULL,
	TEM_PAGTO_INTERMEDIARIO 	CHAR(1) 				NOT NULL,
	INICIO_INTERMED_SEQUENCIA 	NUMBER(9)  					NULL,
	QUANTIDADE_PAGTO_INTERMED 	NUMBER(9)  					NULL,
	TEMPO_ENTRE_PAGTO_INTERMED 	NUMBER(9) 					NULL,
	DESCRICAO_PAGTO 			VARCHAR2(255) 				NULL,
	DESCRICAO_PAGTO_INTERMED 	VARCHAR2(255) 				NULL,
	TEM_PED_EXAME 				CHAR(1) 				NOT NULL
)
;
ALTER TABLE MP_TIPO_PATENTE
	ADD CONSTRAINT PK_TIPO_PATENTE
	PRIMARY KEY(IDTIPO_PATENTE)
;