CREATE TABLE PET_VETERINARIO (
	IDPESSOA			FLOAT			NOT NULL,
	CRMV				VARCHAR(50)		NOT NULL,
	UF					INTEGER			NOT NULL,
	PRIMARY KEY (IDPESSOA),
	FOREIGN KEY(IDPESSOA) REFERENCES NCL_PESSOA(ID)
)
;

CREATE TABLE PET_ANIMAL (
	ID					FLOAT			NOT NULL,
	NOME				VARCHAR(50)		NOT NULL,
	DATADENASCIMENTO	INTEGER				NULL,
	SEXO				CHAR(1)			NOT NULL,
	RACA				VARCHAR(50)		NOT NULL,
	FOTO				VARCHAR(255)		NULL,
	IDPROPRIETARIO		FLOAT			NOT NULL,
	TIPOPESSOA			INTEGER			NOT NULL,
	ESPECIE				CHAR(1)			NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(IDPROPRIETARIO) REFERENCES NCL_PESSOA(ID)
)
;

CREATE INDEX IDX_PET_ANIMAL
	ON PET_ANIMAL(NOME)
;