CREATE TABLE NCL_CNFGERAL (
	NOTIFERROSREMAIL		CHAR(1)			NOT NULL,
	EMAILREMETNOTIFERROS	VARCHAR(255)		NULL,
	REMETENTEPADRAO			VARCHAR(255)		NULL,
	HABILITARSSL			CHAR(1)				NULL,
	PORTA					SMALLINT			NULL,
	REQUERAUTENTICACAO		CHAR(1)				NULL,
	SHNUSUSERVSAIDA			VARCHAR(255)		NULL,
	USUSERVSAIDA			VARCHAR(255)		NULL,
	SERVSAIDA				VARCHAR(255)		NULL,
	TIPOSERVSAIDA			CHAR(1)				NULL,
	TXTCABCOMPRO			VARCHAR(50)		NOT NULL,
	APRELNHCABCOMPRO		CHAR(1)			NOT NULL,
	APRELNHRODCOMPRO		CHAR(1)			NOT NULL,
	TXTCABLEMBRE			VARCHAR(50)		NOT NULL,
	APRELNHCABLEMBRE		CHAR(1)			NOT NULL,
	APRELNHRODLEMBRE		CHAR(1)			NOT NULL,
	TXTCABTARE				VARCHAR(50)		NOT NULL,
	APRELNHCABTARE			CHAR(1)			NOT NULL,
	APRELNHRODTARE			CHAR(1)			NOT NULL
)
;

INSERT INTO NCL_CNFGERAL (NOTIFERROSREMAIL, EMAILREMETNOTIFERROS, REMETENTEPADRAO, HABILITARSSL, PORTA, REQUERAUTENTICACAO, SHNUSUSERVSAIDA, USUSERVSAIDA, SERVSAIDA, TIPOSERVSAIDA, TXTCABCOMPRO, APRELNHCABCOMPRO, APRELNHRODCOMPRO, TXTCABLEMBRE, APRELNHCABLEMBRE, APRELNHRODLEMBRE, TXTCABTARE, APRELNHCABTARE, APRELNHRODTARE)VALUES('S', 'HERMES@SIMPLETI.COM.BR', 'HERMES@SIMPLETI.COM.BR', 'N', 25, 'S', 'CJORP8Z5JEWM4ECX+ENUAG==', 'HERMES@SIMPLETI.COM.BR', 'MAIL.SIMPLETI.COM.BR', '0', 'AGENDA ', 'N', 'N', 'LEMBRETES ', 'N', 'N', 'TAREFAS ', 'N', 'N');