ALTER TABLE MP_MARCAS
 DROP COLUMN DATAPRIMEIRAMANUTENCAO;
 
ALTER TABLE MP_PATENTE
 DROP COLUMN DATAPRIMEIRAMANUTENCAO
 
ALTER TABLE MP_MARCAS
 DROP COLUMN MES;
 
ALTER TABLE MP_PATENTE
 DROP COLUMN MES

ALTER TABLE MP_MARCAS ADD DATAPROXIMAMANUTENCAO INT NULL;
ALTER TABLE MP_PATENTE ADD DATAPROXIMAMANUTENCAO INT NULL;

DROP TABLE MP_BOLETOS_GERADOS;

DROP TABLE MP_BOLETOS_GERADOS_AUX;

DROP TABLE MP_CNFMODGRL;

DELETE FROM NCL_MENUFUNCAO WHERE IDFUNCAO = 'FUN.MP.017';
DELETE FROM NCL_MENUFUNCAO WHERE IDFUNCAO = 'FUN.MP.018';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'FUN.MP.017';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'FUN.MP.018';
DELETE FROM NCL_FUNCAO WHERE IDFUNCAO = 'FUN.MP.017';
DELETE FROM NCL_AUTORIZACAO WHERE IDDIRETIVA = 'OPE.MP.018.0001';
DELETE FROM NCL_OPERACAO WHERE IDFUNCAO = 'FUN.MP.018';
DELETE FROM NCL_FUNCAO WHERE IDFUNCAO = 'FUN.MP.018';
DELETE FROM NCL_ATALHO WHERE ID = 'FUN.MP.017';
DELETE FROM NCL_ATALHO WHERE ID = 'FUN.MP.018';

INSERT INTO NCL_MODULO (IDMODULO, NOME) VALUES ('MOD.FN','Financeiro');
	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.001','Contas a Pagar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.001','OPE.FN.001.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.001','OPE.FN.001.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.001','OPE.FN.001.0003','Excluir');

	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.002','Gerar Boleto avulso');

	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.003','Configurações do Boleto');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.003','OPE.FN.003.0001','Salvar');

INSERT INTO NCL_MENUMODULO (IDMODULO, IMAGEM) VALUES ('MOD.FN','bogus');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.FN','FUN.FN.001','bogus','FN/frmContasAPagar.aspx', NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.FN','FUN.FN.002','bogus','FN/frmBoletoAvulso.aspx',NULL);
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.FN','FUN.FN.003','bogus','FN/frmConfiguracaoDoBoleto.aspx', 'Configurações');
	
CREATE TABLE FN_BOLETOS_GERADOS(
ID	BIGINT NOT NULL,
NUMEROBOLETO BIGINT NOT NULL,
NOSSONUMERO BIGINT NOT NULL,
IDCLIENTE BIGINT NOT NULL,
VALOR FLOAT NOT NULL,
DATAGERACAO VARCHAR(20) NOT NULL,
DATAVENCIMENTO VARCHAR(20) NOT NULL,
OBSERVACAO VARCHAR(4000) NULL);

ALTER TABLE FN_BOLETOS_GERADOS
	ADD CONSTRAINT PK_FN_BOLETOS_GERADOS
	PRIMARY KEY (ID);	
	
ALTER TABLE FN_BOLETOS_GERADOS
	ADD CONSTRAINT FK_FN_BOLETOS_GERADOS_NCL_CLIENTE
	FOREIGN KEY (IDCLIENTE) REFERENCES NCL_CLIENTE(IDPESSOA);

CREATE INDEX IDX_FN_BOLETOS_GERADOS1
	ON FN_BOLETOS_GERADOS(NUMEROBOLETO);
	
CREATE INDEX IDX_FN_BOLETOS_GERADOS2
	ON FN_BOLETOS_GERADOS(IDCLIENTE);

CREATE TABLE FN_BOLETOS_GERADOS_AUX(
ID	BIGINT NOT NULL,
PROXNOSSONUMERO BIGINT NOT NULL,
PROXNUMEROBOLETO BIGINT NOT NULL);

ALTER TABLE FN_BOLETOS_GERADOS_AUX
	ADD CONSTRAINT PK_FN_BOLETOS_GERADOS_AUX
	PRIMARY KEY (ID);	

CREATE TABLE FN_CNFBOLETO (
	IMAGEMBOLETO		VARCHAR(255)		NULL,
	IDCEDENTE			BIGINT				NULL,
	TIPOPESSOA			SMALLINT			NULL
)
;

ALTER TABLE FN_CNFBOLETO
	ADD CONSTRAINT FK_FN_CNFMODGRL1
	FOREIGN KEY(IDCEDENTE)
	REFERENCES NCL_CEDENTE(IDPESSOA)
;

INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.FN','FUN.FN.004','Configurações de índices financeiros');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.FN','FUN.FN.004','OPE.FN.004.0001','Salvar');
INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL, AGRUPADOR) VALUES ('MOD.FN','FUN.FN.004','bogus','FN/frmConfiguracaoDeIndicesFinaceiros.aspx', 'Configurações');

CREATE TABLE FN_CNFINDFINAN (
	VALORSALMIN			FLOAT			NULL
);

ALTER TABLE FN_BOLETOS_GERADOS_AUX DROP COLUMN PROXNUMEROBOLETO;

DROP INDEX FN_BOLETOS_GERADOS.IDX_FN_BOLETOS_GERADOS1;

ALTER TABLE FN_BOLETOS_GERADOS ALTER COLUMN NUMEROBOLETO VARCHAR(50) NULL;