ALTER TABLE NCL_CEDENTE ADD TIPODECARTEIRA VARCHAR(50);

ALTER TABLE NCL_CEDENTE ADD INICIONOSSONUMERO BIGINT;

ALTER TABLE FN_ITEMFINANREC ADD IDBOLETO BIGINT;

CREATE TABLE NCL_PESSOAEVENTO (
	IDPESSOA			BIGINT			NOT NULL,
	DATA				INT				NOT NULL,
	DESCRICAO			VARCHAR(4000)	NOT NULL
)
;

ALTER TABLE NCL_PESSOAEVENTO
	ADD CONSTRAINT FK_NCL_PESSOAEVENTO1
	FOREIGN KEY(IDPESSOA)
	REFERENCES NCL_PESSOA(ID)
;

CREATE INDEX IDX_NCL_PESSOAEVENTO1
	ON NCL_PESSOAEVENTO(IDPESSOA)
;