ALTER TABLE MP_MARCAS
 DROP COLUMN DATAPRIMEIRAMANUTENCAO;
 
ALTER TABLE MP_PATENTE
 DROP COLUMN DATAPRIMEIRAMANUTENCAO
 
ALTER TABLE MP_MARCAS
 DROP COLUMN MES;
 
ALTER TABLE MP_PATENTE
 DROP COLUMN MES

ALTER TABLE MP_MARCAS ADD DATAPROXIMAMANUTENCAO INT NULL;
ALTER TABLE MP_PATENTE ADD DATAPROXIMAMANUTENCAO INT NULL;