INSERT INTO NCL_MODULO (IDMODULO, NOME) VALUES ('MOD.DRY','Diary');
	INSERT INTO NCL_FUNCAO (IDMODULO, IDFUNCAO, NOME) VALUES ('MOD.DRY','FUN.DRY.001','Cadastro de contato');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.001','OPE.DRY.001.0001','Inserir');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.001','OPE.DRY.001.0002','Modificar');
		INSERT INTO NCL_OPERACAO (IDMODULO, IDFUNCAO, IDOPERACAO, NOME) VALUES ('MOD.DRY','FUN.DRY.001','OPE.DRY.001.0003','Excluir');
					
INSERT INTO NCL_MENUMODULO (IDMODULO, IMAGEM) VALUES ('MOD.DRY','bogus');
	INSERT INTO NCL_MENUFUNCAO (IDMODULO, IDFUNCAO, IMAGEM, URL) VALUES ('MOD.DRY','FUN.DRY.001','bogus','Diary/cdContato.aspx');